// Flat ESLint config for the Clara monorepo (ESLint 9 + typescript-eslint).
//
// Scope of enforcement, by file kind:
//   - ALL TypeScript      → typescript-eslint's non-type-checked `recommended`.
//   - packages/runtime .ts → ADDS the two TYPE-CHECKED promise-safety rules
//     (no-floating-promises + no-misused-promises). The runtime orchestrates
//     durable async work, so a dropped or mis-passed promise is a real
//     correctness risk — worth the cost of a typed lint pass here. Type
//     information comes from `projectService` (each file's nearest tsconfig).
//   - Plain-ESM JavaScript (packages/db scripts, worker.mjs, next.config.mjs,
//     this file) → @eslint/js `recommended` only. The typed promise rules are
//     N/A without a tsc program, so they simply aren't enabled for JS.
//   - Build output, deps, generated types, and the frozen spike/ are ignored.
//
// Each package exposes `"lint": "eslint ."`; the root `pnpm lint` fans out via
// `pnpm -r --if-present lint`, and ESLint walks up from each package to THIS
// config. Adding a rule here changes every package at once.

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // Global ignores — an object with ONLY `ignores` applies to the whole run.
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.output/**",
      "**/.nitro/**",
      "**/.next/**",
      "**/coverage/**",
      "**/*.tsbuildinfo",
      // The Slice-0 runtime spike is a frozen throwaway with its own toolchain.
      "spike/**",
      // Generated by `next` — not hand-edited, carries its own triple-slash refs.
      "apps/dashboard/next-env.d.ts",
    ],
  },

  // Plain-ESM JavaScript (Node data-plane scripts, worker, next config).
  {
    files: ["**/*.{js,mjs,cjs}"],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node },
    },
  },

  // All TypeScript — non-type-checked recommended baseline.
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [tseslint.configs.recommended],
  },

  // Runtime TypeScript only — layer the two TYPE-CHECKED promise-safety rules.
  {
    files: ["packages/runtime/**/*.ts"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
    },
  },
);
