// Flat ESLint config for the Clara monorepo (ESLint 9 + typescript-eslint).
//
// Scope of enforcement, by file kind:
//   - ALL TypeScript      → typescript-eslint's non-type-checked `recommended`.
//   - packages/runtime .ts → ADDS the two TYPE-CHECKED promise-safety rules
//     (no-floating-promises + no-misused-promises). The runtime orchestrates
//     durable async work, so a dropped or mis-passed promise is a real
//     correctness risk — worth the cost of a typed lint pass here. Type
//     information comes from `projectService` (each file's nearest tsconfig).
//   - Plain-ESM JavaScript (packages/db scripts, worker.mjs, next.config.mjs,
//     this file) → @eslint/js `recommended` only. The typed promise rules are
//     N/A without a tsc program, so they simply aren't enabled for JS.
//   - Build output, deps, generated types, and the frozen spike/ are ignored.
//
// Each package exposes `"lint": "eslint ."`; the root `pnpm lint` fans out via
// `pnpm -r --if-present lint`, and ESLint walks up from each package to THIS
// config. Adding a rule here changes every package at once.

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // Global ignores — an object with ONLY `ignores` applies to the whole run.
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.output/**",
      "**/.nitro/**",
      "**/.next/**",
      "**/coverage/**",
      "**/*.tsbuildinfo",
      // The Slice-0 runtime spike is a frozen throwaway with its own toolchain.
      "spike/**",
      // Generated by `next` — not hand-edited, carries its own triple-slash refs.
      "apps/dashboard/next-env.d.ts",
    ],
  },

  // Plain-ESM JavaScript (Node data-plane scripts, worker, next config).
  {
    files: ["**/*.{js,mjs,cjs}"],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node },
    },
  },

  // All TypeScript — non-type-checked recommended baseline.
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [tseslint.configs.recommended],
  },

  // SPLIT-WAVE FORKS — `no-unused-vars` off, and ONLY that rule.
  //
  // A fork (`x<NN>b<S>-*.test.mjs`) is a slice's share of a test file whose cells span more
  // than one migration slice. It is produced MECHANICALLY (`slices/forks/work/forktool.py`),
  // and the tool's whole safety argument is that it MOVES cells and never EDITS them: a
  // fork's prologue is byte-identical to its parent's, so every fork of a file imports the
  // same fixtures, in the same order, with the same names — and the tool asserts that
  // invariant (plus cell conservation: 418 cells, no cell assigned twice) as its own
  // correctness check. A fork therefore carries bindings only the SIBLING slice's cells use.
  // They are the declared, measured cost of the idiom, not oversights.
  //
  // Trimming them by hand would break the property the split is verified on and make the
  // forks non-regenerable — the byte-identical prologue is the evidence, so the lint yields
  // here rather than the evidence. Scoped to the fork filename pattern, and to this one rule,
  // so the wave's OWN new files (`x42-*`, `x42x-*`) stay fully linted: the two genuine
  // findings in those were fixed at source, not silenced.
  {
    files: ["packages/db/tests/x4[0-9]b[0-9]-*.test.mjs"],
    rules: { "no-unused-vars": "off" },
  },

  // Runtime TypeScript only — layer the two TYPE-CHECKED promise-safety rules.
  {
    files: ["packages/runtime/**/*.ts"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
    },
  },
);
