// @frozen
//
// FROZEN — part of the autoDraft_v7 closure (WAVE E, the F6–F9 fix batch; H1 ACCEPTANCE
// FINDING F9, ADR-064 §3). A NEW frozen closure beside the byte-untouched
// autoDraft_v1..v6 (ARCHITECTURE Appendix A: a behavioural change ships as a new _vN
// export, never an in-place edit — the registry repoints `autoDraft:` here).
//
// THE FINDING, ONCE, FOR THE WHOLE CLOSURE. The drafting model mis-transcribed ONE hex
// group of a 36-character region UUID (…-4c6d-… for the true …-4fce-…), recurring across
// independent attempts, and the DB evidence wall (clara._write_entry_evidence) correctly
// refused CLR21 evidence_invalid every time — its id-equality contract is right, and a
// hand-draft citing the true id drafted clean first try
// (docs/plan/wave-7a-acceptance-h1.md:773-790). The defect is upstream, in asking a model
// to reproduce an opaque 36-char identifier it was shown once inside a large JSON array.
// v7 stops asking: the toolface takes a small INDEX (`region_idx`) into the region list
// read_document printed, and the WRAPPER resolves index -> region_id server-side before
// the DB writer is called. The wall is untouched and still receives a region_id.
//
// THIS FILE (the workflow entry) — an UNMODIFIED version-rename of v6: the
// claim/recover/model/settle/question/close happy path, refusalFromCaughtError and its
// WDK retry-prefix pattern, and the finally block are byte-identical; only the import
// paths and the exported symbol name moved. Do NOT edit this file or its import closure
// (autoDraft.v7.impl / .tools / .infra / .prompt / .errors) once deployed — ship a
// behavioural change as autoDraft_v8.

import {
  AUTODRAFT_MODEL_ERROR_TAG,
  claimAutoDraftStep,
  recoverAutoDraftStep,
  runAutoDraftModelStep,
  settleAutoDraftStep,
  openSweepQuestionStep,
  closeAutoDraftStreamStep,
} from "./autoDraft.v7.impl.js";
import { isQuestionShaped } from "./autoDraft.v7.prompt.js";
import { noDraftRefusal } from "./autoDraft.v7.errors.js";

/** The EXACT literal shape step-handler.js:507 prepends on retry exhaustion — `Step "<any
 *  step name>" failed after <N> retry`/`retries`: ` — matched literally (a quoted step
 *  name, a digit count, the two pluralize('retry','retries',N) outputs), never a wildcard
 *  gap, so this can only recognise WDK's OWN exact wrapper text, nothing merely similar. */
const WDK_RETRY_PREFIX_SOURCE = `Step "[^"]*" failed after \\d+ retr(?:y|ies): `;

/** Matches consumeAutoDraftModelResult's own `[autodraft_model:<code>] <message>` tag at
 *  EITHER of exactly two positions — the message's own start, or immediately after WDK's
 *  retry-exhaustion prefix (R-round F1: that prefix is what step-handler.js actually
 *  prepends before the tag ever reaches step.js's FatalError reconstruction). The pattern
 *  stays `^`-anchored across BOTH branches, with the prefix branch matched by the literal
 *  shape above rather than `.*` or any other free-floating scan — an arbitrary vendor
 *  message that happens to CONTAIN the tag text somewhere in its middle, with no exact
 *  prefix immediately before it, can never match. This is deliberate: an unanchored search
 *  would let a vendor's own error text forge a settle-record diagnostic code. */
const AUTODRAFT_MODEL_ERROR_PATTERN = new RegExp(
  `^(?:${WDK_RETRY_PREFIX_SOURCE})?\\[${AUTODRAFT_MODEL_ERROR_TAG}:([^\\]]+)\\]\\s(.*)$`,
  "s",
);

/** ledger #44 (the third swallow + the R-round F1 fix): reduce a caught top-level error into
 *  the settle record's refusal shape. A message carrying consumeAutoDraftModelResult's own
 *  `[autodraft_model:<code>]` tag is parsed back into {code, message} — the tag, not the
 *  `.code` property, since `.code` never survives a step-originated failure crossing the WDK
 *  boundary (see this file's own header). Anything else falls back to the error's own `.code`
 *  property when present (harmless, though no current caller in this function crosses zero
 *  step boundaries), then to "internal". "sweep draft failed" is the TRUE last resort (an
 *  empty/unreadable message), never the default. Pure — no WDK-ambient call, directly
 *  unit-testable. */
export function refusalFromCaughtError(err: unknown): { code: string; message: string } {
  const rawMessage = err instanceof Error ? err.message : String(err);
  const tagged = AUTODRAFT_MODEL_ERROR_PATTERN.exec(rawMessage);
  if (tagged) {
    // The regex's own two capture groups both matched for `tagged` to be non-null at all —
    // the `?? "internal"` on group 1 is defensive typing hygiene only, never expected to fire.
    return { code: tagged[1] ?? "internal", message: tagged[2] || "sweep draft failed" };
  }
  const code =
    err && typeof err === "object" && "code" in err && typeof (err as { code?: unknown }).code === "string"
      ? (err as { code: string }).code
      : "internal";
  return { code, message: rawMessage || "sweep draft failed" };
}

export async function autoDraft_v7(input: { taskId: string }): Promise<{ taskId: string; outcome: string }> {
  "use workflow";
  const taskId = input.taskId;
  let settled = false;
  const settle = async (
    outcome: "drafted" | "skipped_lane" | "noop_existing" | "failed",
    tokens: number,
    entryId: string | null,
    refusal: unknown | null,
  ) => {
    if (settled) return;
    settled = true;
    await settleAutoDraftStep(taskId, outcome, tokens, entryId, refusal);
  };

  try {
    const claim = await claimAutoDraftStep(taskId);
    if (!claim.claimed || !claim.ctx) return { taskId, outcome: "deduped" };
    const ctx = {
      firmId: claim.ctx.firmId,
      clientId: claim.ctx.clientId,
      documentId: claim.ctx.documentId,
      filingId: claim.ctx.filingId,
      taskId,
      direction: claim.ctx.direction,
    };

    // Kill-after-draft resume: a persisted attempt short-circuits to the drafted settle.
    const recovered = await recoverAutoDraftStep(taskId);
    if (recovered) {
      await settle("drafted", 0, recovered.entry_id, null);
      return { taskId, outcome: "drafted" };
    }

    const seg = await runAutoDraftModelStep(ctx, claim.ctx.model);
    const outcome = seg.outcome;

    if (outcome.kind === "drafted") {
      await settle("drafted", seg.usageTokens, outcome.entryId, null);
      return { taskId, outcome: "drafted" };
    }
    if (outcome.kind === "noop_existing") {
      // BOTH double_coded reasons -> success-shaped settle (WA-L8): the bill is already coded.
      await settle("noop_existing", seg.usageTokens, null, { code: "CLR29", reason: outcome.reason });
      return { taskId, outcome: "noop_existing" };
    }

    // No lawful draft. A question-shaped block opens a scoped open-question, then a failed
    // settle records the refusal; any other block settles failed with a terminal refusal.
    const refusal = outcome.kind === "refused" ? outcome.refusal : noDraftRefusal();
    if (outcome.kind === "refused" && isQuestionShaped(outcome.refusal)) {
      await openSweepQuestionStep(ctx, outcome.refusal.message);
    }
    await settle("failed", seg.usageTokens, null, refusal);
    return { taskId, outcome: "failed" };
  } catch (err) {
    await settle("failed", 0, null, refusalFromCaughtError(err)).catch(() => {});
    throw err instanceof Error ? err : new Error(String(err));
  } finally {
    await closeAutoDraftStreamStep().catch(() => {});
  }
}
