// @frozen
//
// FROZEN — the autoDraft_v10 workflow entry (H-17: the unattended coder refused itself on a
// sales invoice and opened a human question no answer could settle; see autoDraft.v10.tools.ts
// for the one statement of what v10 changes and autoDraft.v10.uniques.ts for the argument). A
// NEW frozen closure beside the byte-untouched autoDraft_v1..v9 (ARCHITECTURE Appendix A: a
// behavioural change ships as a new _vN export, never an in-place edit — the registry repoints
// the autoDraft key here). autoDraft_v9 stays EXPORTED and frozen; a parked run resumes
// into the body it started with, and v9's parks are the ordinary kind.
//
// THIS FILE IS A VERSION-RENAME of autoDraft.v9.ts: the export name, and two import lines that
// name their v10 siblings. The body — claim / recover / model / the two POST branches / question
// / close, refusalFromCaughtError with its WDK retry-prefix pattern, and the finally block — is
// v9's, unchanged line for line.
//
// WHAT v10's CHANGE MEANS AT THIS LAYER, since this is where the consequence lands. v9 mapped
// three different counterparty-identity uniques onto ONE untokened CLR23, and isQuestionShaped
// returns true for every CLR23 (autoDraft.v9.prompt.ts:466-477) — so the refused branch at the
// bottom of this function called openSweepQuestionStep with a sentence that answered none of
// them. Under v10 only the REGISTRATION collision still reaches that branch; the alias and
// unregistered-name collisions arrive coded 'transient', which is not question-shaped, so they
// settle failed with a durable, actionable reason and open no question at all. Nothing in this
// file moved to make that true — the vocabulary did.
//
// Do NOT edit this file or its import closure (autoDraft.v10.impl / .tools / .toolset / .errors
// / .uniques, plus v9's .post / .postcall / .settle / .infra / .prompt / .usage, which v10
// reuses) once deployed — ship a behavioural change as autoDraft_v11.

import {
  AUTODRAFT_MODEL_ERROR_TAG,
  claimAutoDraftStep,
  recoverAutoDraftStep,
  runAutoDraftModelStep,
  settleAutoDraftStep,
  openSweepQuestionStep,
  closeAutoDraftStreamStep,
} from "./autoDraft.v10.impl.js";
import { isQuestionShaped } from "./autoDraft.v9.prompt.js";
import { noDraftRefusal } from "./autoDraft.v10.errors.js";

/** The EXACT literal shape step-handler.js:507 prepends on retry exhaustion — `Step "<any
 *  step name>" failed after <N> retry`/`retries`: ` — matched literally (a quoted step
 *  name, a digit count, the two pluralize('retry','retries',N) outputs), never a wildcard
 *  gap, so this can only recognise WDK's OWN exact wrapper text, nothing merely similar. */
const WDK_RETRY_PREFIX_SOURCE = `Step "[^"]*" failed after \\d+ retr(?:y|ies): `;

/** Matches consumeAutoDraftModelResult's own `[autodraft_model:<code>] <message>` tag at
 *  EITHER of exactly two positions — the message's own start, or immediately after WDK's
 *  retry-exhaustion prefix (R-round F1: that prefix is what step-handler.js actually
 *  prepends before the tag ever reaches step.js's FatalError reconstruction). The pattern
 *  stays `^`-anchored across BOTH branches, with the prefix branch matched by the literal
 *  shape above rather than `.*` or any other free-floating scan — an arbitrary vendor
 *  message that happens to CONTAIN the tag text somewhere in its middle, with no exact
 *  prefix immediately before it, can never match. This is deliberate: an unanchored search
 *  would let a vendor's own error text forge a settle-record diagnostic code. */
const AUTODRAFT_MODEL_ERROR_PATTERN = new RegExp(
  `^(?:${WDK_RETRY_PREFIX_SOURCE})?\\[${AUTODRAFT_MODEL_ERROR_TAG}:([^\\]]+)\\]\\s(.*)$`,
  "s",
);

/** ledger #44 (the third swallow + the R-round F1 fix): reduce a caught top-level error into
 *  the settle record's refusal shape. A message carrying consumeAutoDraftModelResult's own
 *  `[autodraft_model:<code>]` tag is parsed back into {code, message} — the tag, not the
 *  `.code` property, since `.code` never survives a step-originated failure crossing the WDK
 *  boundary (see this file's own header). Anything else falls back to the error's own `.code`
 *  property when present (harmless, though no current caller in this function crosses zero
 *  step boundaries), then to "internal". "sweep draft failed" is the TRUE last resort (an
 *  empty/unreadable message), never the default. Pure — no WDK-ambient call, directly
 *  unit-testable. */
export function refusalFromCaughtError(err: unknown): { code: string; message: string } {
  const rawMessage = err instanceof Error ? err.message : String(err);
  const tagged = AUTODRAFT_MODEL_ERROR_PATTERN.exec(rawMessage);
  if (tagged) {
    // The regex's own two capture groups both matched for `tagged` to be non-null at all —
    // the `?? "internal"` on group 1 is defensive typing hygiene only, never expected to fire.
    return { code: tagged[1] ?? "internal", message: tagged[2] || "sweep draft failed" };
  }
  const code =
    err && typeof err === "object" && "code" in err && typeof (err as { code?: unknown }).code === "string"
      ? (err as { code: string }).code
      : "internal";
  return { code, message: rawMessage || "sweep draft failed" };
}

export async function autoDraft_v10(input: { taskId: string }): Promise<{ taskId: string; outcome: string }> {
  "use workflow";
  const taskId = input.taskId;
  let settled = false;
  const settle = async (
    outcome: "drafted" | "skipped_lane" | "noop_existing" | "failed" | "posted",
    tokens: number,
    entryId: string | null,
    refusal: unknown | null,
  ) => {
    if (settled) return;
    settled = true;
    await settleAutoDraftStep(taskId, outcome, tokens, entryId, refusal);
  };

  try {
    const claim = await claimAutoDraftStep(taskId);
    if (!claim.claimed || !claim.ctx) return { taskId, outcome: "deduped" };
    const ctx = {
      firmId: claim.ctx.firmId,
      clientId: claim.ctx.clientId,
      documentId: claim.ctx.documentId,
      filingId: claim.ctx.filingId,
      taskId,
      direction: claim.ctx.direction,
    };

    // Kill-after-draft resume: a persisted attempt short-circuits to the drafted settle.
    const recovered = await recoverAutoDraftStep(taskId);
    if (recovered) {
      await settle("drafted", 0, recovered.entry_id, null);
      return { taskId, outcome: "drafted" };
    }

    const seg = await runAutoDraftModelStep(ctx, claim.ctx.model);
    const outcome = seg.outcome;

    // ============================ F-A2: THE TWO POST OUTCOMES ================================
    //
    // NO BACKTICKS IN THIS FILE'S COMMENTS, AND THAT IS NOT A STYLE RULE. The Workflow DevKit
    // detects a "use workflow" directive by blanking template literals with a NAIVE regex before
    // it looks for the directive line — so a stray backtick in a comment above the directive can
    // pair with one below it and blank the directive itself. The build then succeeds, the file
    // is silently left untransformed, and the workflow is simply ABSENT from the registry. This
    // file hit exactly that, caught by the mandatory bundle grep; the whole closure's prose uses
    // plain quotes here as a result. Sibling modules with no directive are unaffected.
    //
    // ORDER IS LOAD-BEARING, AND PR-1's OWN MIGRATION SAYS SO IN WORDS: "PR-2's producer must
    // settle only AFTER the post commits." That is satisfied structurally rather than by care —
    // runAutoDraftModelStep is a WDK step, so the post transaction it ran has already committed
    // before this line can execute at all. A settle written inside the model step, beside the
    // post, would have been the defect: a posted settle that lands and then rolls back leaves
    // sweep_run_items claiming a post that is not in the books.
    //
    // A POSTED RUN SETTLES 'posted', NEVER 'drafted'. Folding it into drafted was weighed and is
    // refused for the same reason R-L5 refused folding posted_count into drafted_count: §6 reads
    // this surface, and a posted run that is indistinguishable from a drafted one makes the
    // acceptance number unmeasurable. The entry id is REQUIRED here — the DB's re-cut
    // ck_sweep_run_items_shape demands it on a posted row.
    if (outcome.kind === "posted") {
      await settle("posted", seg.usageTokens, outcome.entryId, null);
      return { taskId, outcome: "posted" };
    }

    // A REFUSED POST. The draft EXISTS — the post was attempted against it and the ladder said
    // no — so the honest settle is 'drafted', carrying the refusal so the reason is durable and
    // the bookkeeper sees WHY it is still sitting in the review queue. Two exceptions:
    //   * Tier D is a COMMIT abort, not an admission verdict, so it settles 'failed' with the
    //     (errcode, reason) captured verbatim in last_refusal (design E.2, GM-3).
    //   * a post refused with no entry id recorded cannot settle 'drafted' at all, because the
    //     DB requires an entry id on that outcome; it settles 'failed', which is the truthful
    //     answer to "which entry did this run leave behind" when the run cannot say.
    if (outcome.kind === "post_refused") {
      if (outcome.tier === "D" || !outcome.entryId) {
        await settle("failed", seg.usageTokens, null, outcome.lastRefusal);
        return { taskId, outcome: "failed" };
      }
      await settle("drafted", seg.usageTokens, outcome.entryId, outcome.refusal);
      return { taskId, outcome: "drafted" };
    }

    if (outcome.kind === "drafted") {
      await settle("drafted", seg.usageTokens, outcome.entryId, null);
      return { taskId, outcome: "drafted" };
    }
    if (outcome.kind === "noop_existing") {
      // BOTH double_coded reasons -> success-shaped settle (WA-L8): the bill is already coded.
      await settle("noop_existing", seg.usageTokens, null, { code: "CLR29", reason: outcome.reason });
      return { taskId, outcome: "noop_existing" };
    }

    // No lawful draft. A question-shaped block opens a scoped open-question, then a failed
    // settle records the refusal; any other block settles failed with a terminal refusal.
    const refusal = outcome.kind === "refused" ? outcome.refusal : noDraftRefusal();
    if (outcome.kind === "refused" && isQuestionShaped(outcome.refusal)) {
      await openSweepQuestionStep(ctx, outcome.refusal.message);
    }
    await settle("failed", seg.usageTokens, null, refusal);
    return { taskId, outcome: "failed" };
  } catch (err) {
    await settle("failed", 0, null, refusalFromCaughtError(err)).catch(() => {});
    throw err instanceof Error ? err : new Error(String(err));
  } finally {
    await closeAutoDraftStreamStep().catch(() => {});
  }
}
