// @frozen
//
// BINDING versioning policy (ARCHITECTURE Appendix A): a deployed workflow body is IMMUTABLE
// once any run can be in flight. autoDraft_v6 is a NEW frozen closure (registry repoints
// `autoDraft: autoDraft_v6`); autoDraft_v5/v4/v3/v2/v1 and every other export are byte-untouched.
// Do NOT edit this file or its import closure (autoDraft.v6.impl / .tools / .infra / .prompt /
// .errors) once deployed — ship a behavioural change as autoDraft_v7.
//
// autoDraft_v6 (§7-A THE UNATTENDED SALES DRAFTER, wave-7a-contract.md, ADR-063): the
// claim/recover/model/settle/question/close happy path, the catch block's
// refusalFromCaughtError delegation, and the finally block are otherwise byte-identical to
// v5. This wave's functional changes live mostly OUTSIDE this file:
// autoDraft.v6.prompt.ts's coding_kind menu + counterparty generalisation + sales leg-shape
// guidance, autoDraft.v6.tools.ts's coding_kind passthrough + counterparty-kind derivation +
// (PR #204) the bound-family early-validation check, autoDraft.v6.errors.ts's five new
// refusal tokens + direction-neutral generics, and autoDraft.v6.impl.ts's settle call moving
// to the 6-arity settle_autodraft_task overload plus (PR #204) its own settled===false no-op
// handling (full rationale in each file's own header). The ONE change actually IN this file:
// the `ctx` object built after a successful claim now carries `direction: claim.ctx.
// direction` through to runAutoDraftModelStep — PR #204's bound-direction fact, read by
// claimAutoDraftStep, consumed by both the model step (the user-message hint) and the
// wrapper (the early family check).
//
// Schema + steps are otherwise byte-identical to v5: one admitted READY document per task:
// claim (begin_autodraft_task: CAS queued->running + context + reserved tokens) -> recover a
// completed attempt (kill-after-draft resume, no re-model) -> run the coding model
// client-pinned (drafts ONLY) -> settle_autodraft_task with actuals. BOTH double_coded reasons
// map to a SUCCESS-shaped noop_existing settle (WA-L8). A question-shaped non-draft MAY open a
// scoped open-question (origin sweep_refusal) then settles failed with the refusal.
// Kill/replay-safe at every step boundary (begin/settle are idempotent; the model step is
// guarded by the op_key + the get_coding_attempt recovery).

import {
  AUTODRAFT_MODEL_ERROR_TAG,
  claimAutoDraftStep,
  recoverAutoDraftStep,
  runAutoDraftModelStep,
  settleAutoDraftStep,
  openSweepQuestionStep,
  closeAutoDraftStreamStep,
} from "./autoDraft.v6.impl.js";
import { isQuestionShaped } from "./autoDraft.v6.prompt.js";
import { noDraftRefusal } from "./autoDraft.v6.errors.js";

/** The EXACT literal shape step-handler.js:507 prepends on retry exhaustion — `Step "<any
 *  step name>" failed after <N> retry`/`retries`: ` — matched literally (a quoted step
 *  name, a digit count, the two pluralize('retry','retries',N) outputs), never a wildcard
 *  gap, so this can only recognise WDK's OWN exact wrapper text, nothing merely similar. */
const WDK_RETRY_PREFIX_SOURCE = `Step "[^"]*" failed after \\d+ retr(?:y|ies): `;

/** Matches consumeAutoDraftModelResult's own `[autodraft_model:<code>] <message>` tag at
 *  EITHER of exactly two positions — the message's own start, or immediately after WDK's
 *  retry-exhaustion prefix (R-round F1: that prefix is what step-handler.js actually
 *  prepends before the tag ever reaches step.js's FatalError reconstruction). The pattern
 *  stays `^`-anchored across BOTH branches, with the prefix branch matched by the literal
 *  shape above rather than `.*` or any other free-floating scan — an arbitrary vendor
 *  message that happens to CONTAIN the tag text somewhere in its middle, with no exact
 *  prefix immediately before it, can never match. This is deliberate: an unanchored search
 *  would let a vendor's own error text forge a settle-record diagnostic code. */
const AUTODRAFT_MODEL_ERROR_PATTERN = new RegExp(
  `^(?:${WDK_RETRY_PREFIX_SOURCE})?\\[${AUTODRAFT_MODEL_ERROR_TAG}:([^\\]]+)\\]\\s(.*)$`,
  "s",
);

/** ledger #44 (the third swallow + the R-round F1 fix): reduce a caught top-level error into
 *  the settle record's refusal shape. A message carrying consumeAutoDraftModelResult's own
 *  `[autodraft_model:<code>]` tag is parsed back into {code, message} — the tag, not the
 *  `.code` property, since `.code` never survives a step-originated failure crossing the WDK
 *  boundary (see this file's own header). Anything else falls back to the error's own `.code`
 *  property when present (harmless, though no current caller in this function crosses zero
 *  step boundaries), then to "internal". "sweep draft failed" is the TRUE last resort (an
 *  empty/unreadable message), never the default. Pure — no WDK-ambient call, directly
 *  unit-testable. */
export function refusalFromCaughtError(err: unknown): { code: string; message: string } {
  const rawMessage = err instanceof Error ? err.message : String(err);
  const tagged = AUTODRAFT_MODEL_ERROR_PATTERN.exec(rawMessage);
  if (tagged) {
    // The regex's own two capture groups both matched for `tagged` to be non-null at all —
    // the `?? "internal"` on group 1 is defensive typing hygiene only, never expected to fire.
    return { code: tagged[1] ?? "internal", message: tagged[2] || "sweep draft failed" };
  }
  const code =
    err && typeof err === "object" && "code" in err && typeof (err as { code?: unknown }).code === "string"
      ? (err as { code: string }).code
      : "internal";
  return { code, message: rawMessage || "sweep draft failed" };
}

export async function autoDraft_v6(input: { taskId: string }): Promise<{ taskId: string; outcome: string }> {
  "use workflow";
  const taskId = input.taskId;
  let settled = false;
  const settle = async (
    outcome: "drafted" | "skipped_lane" | "noop_existing" | "failed",
    tokens: number,
    entryId: string | null,
    refusal: unknown | null,
  ) => {
    if (settled) return;
    settled = true;
    await settleAutoDraftStep(taskId, outcome, tokens, entryId, refusal);
  };

  try {
    const claim = await claimAutoDraftStep(taskId);
    if (!claim.claimed || !claim.ctx) return { taskId, outcome: "deduped" };
    const ctx = {
      firmId: claim.ctx.firmId,
      clientId: claim.ctx.clientId,
      documentId: claim.ctx.documentId,
      filingId: claim.ctx.filingId,
      taskId,
      direction: claim.ctx.direction,
    };

    // Kill-after-draft resume: a persisted attempt short-circuits to the drafted settle.
    const recovered = await recoverAutoDraftStep(taskId);
    if (recovered) {
      await settle("drafted", 0, recovered.entry_id, null);
      return { taskId, outcome: "drafted" };
    }

    const seg = await runAutoDraftModelStep(ctx, claim.ctx.model);
    const outcome = seg.outcome;

    if (outcome.kind === "drafted") {
      await settle("drafted", seg.usageTokens, outcome.entryId, null);
      return { taskId, outcome: "drafted" };
    }
    if (outcome.kind === "noop_existing") {
      // BOTH double_coded reasons -> success-shaped settle (WA-L8): the bill is already coded.
      await settle("noop_existing", seg.usageTokens, null, { code: "CLR29", reason: outcome.reason });
      return { taskId, outcome: "noop_existing" };
    }

    // No lawful draft. A question-shaped block opens a scoped open-question, then a failed
    // settle records the refusal; any other block settles failed with a terminal refusal.
    const refusal = outcome.kind === "refused" ? outcome.refusal : noDraftRefusal();
    if (outcome.kind === "refused" && isQuestionShaped(outcome.refusal)) {
      await openSweepQuestionStep(ctx, outcome.refusal.message);
    }
    await settle("failed", seg.usageTokens, null, refusal);
    return { taskId, outcome: "failed" };
  } catch (err) {
    await settle("failed", 0, null, refusalFromCaughtError(err)).catch(() => {});
    throw err instanceof Error ? err : new Error(String(err));
  } finally {
    await closeAutoDraftStreamStep().catch(() => {});
  }
}
