// @frozen
//
// FROZEN — part of the bankAgent_v1 closure (Gate G1's bank follow-up: the workflow body the
// wake engine dispatches for the 'bank_agent' source). A NEW frozen workflow CLASS, not a new
// version of an existing one — packages/runtime/plugins/startWorld.ts's own note that "no
// bankAgent/closePrep export exists yet" is what this closure makes false-to-fact.
// ARCHITECTURE Appendix A: once deployed, do not edit this file or any member of its import
// closure (bankAgent.v1 / .impl / .tools / .prompt / .usage) — ship a behavioural change as
// bankAgent_v2.
//
// THIS FILE (infra) — the pool/credential/model plumbing plus the two DB acts that are NOT
// bank verbs: the task CLAIM and the task SETTLE. Both live INSIDE the frozen closure on
// purpose. The claim is judgement logic (it decides whether this run may act at all), and the
// runtime-workflows rule's own principle — "the prompt and the tools live inside the frozen
// closure by design" — applies with more force to a guard than to a prompt: a guard that could
// be edited underneath a deployed body is not a guard.
//
// WHAT THE CLAIM CLOSES (design g1-wake-engine-design.md §1.2d, and wake-engine.mjs's own
// module header #5/#8, which names this file's obligation explicitly as "VERIFIED, NOT YET
// GUARDED" pending exactly this build):
//   #5 the unknown-abort. A cancel can land between the engine's enqueue() commit and this
//      run's first bind of workflow_run_id. While that column is NULL, reconciler.mjs's own
//      cancel branch cannot tell "never started" from "started, not yet bound", and settles the
//      task 'cancelled' immediately. A live run that kept acting would then be acting under
//      books that already say it stopped.
//   #8 the duplicate start. reconciler-wake.mjs §A re-enqueues a running-with-no-run row past
//      grace; a crash-recovery replay can therefore start a SECOND run for one task.
// ONE guard closes both, and it is the SAME "duplicate start self-aborts" idiom
// reconciler-wake.mjs's own header already invokes: the first durable step re-reads its own
// task's CURRENT status and refuses to proceed — a clean no-op exit, never a thrown error —
// unless it is still 'running' and unbound-or-bound-to-THIS-run.

import { openai } from "@ai-sdk/openai";

export type PgExec = {
  query(sql: string, params?: unknown[]): Promise<{ rows: Array<Record<string, unknown>>; rowCount: number | null }>;
};

/** The members of the injected pool bundle this closure actually uses. The bundle is reached
 *  through globalThis (never imported) so infrastructure tuning is not a workflow-version
 *  change — the estate's standing idiom, autoDraft.v9.infra.ts's own shape. */
export type BankPools = {
  withRuntime<T>(fn: (c: PgExec) => Promise<T>): Promise<T>;
  withBankWakeScoped<T>(secret: string, fn: (c: PgExec) => Promise<T>): Promise<T>;
  mintBankAgentCredential(firmId: string, clientId: string, ttl?: string): Promise<{ secret: string }>;
};

export function pools(): BankPools {
  const p = (globalThis as unknown as { __claraPools?: BankPools }).__claraPools;
  if (!p) throw new Error("runtime pools not injected (globalThis.__claraPools) — the supervisor must inject them at boot");
  return p;
}

/** The short TTL minted for one execution attempt. Never outlives the attempt that minted it. */
export const BANK_CREDENTIAL_TTL = process.env.CLARA_BANK_CREDENTIAL_TTL || "5 minutes";

/** The task context a claimed bank run acts under. `bankAccountId` is read off the ORIGINATING
 *  DOMAIN EVENT's payload, never chosen by the model and never guessed — see readBankTaskContext. */
export type BankTaskContext = {
  taskId: string;
  firmId: string;
  clientId: string;
  bankAccountId: string;
  dueReason: string | null;
};

/**
 * THE THREE VERDICTS, and the distinction between the last two is load-bearing.
 *
 * `claimed`   — this run holds the task and has a usable context. Act, then settle.
 * `stand_down` — the CAS refused: the task is not 'running' any more, or it is bound to a
 *                DIFFERENT run. This run holds NOTHING, so it must settle NOTHING — a settle
 *                from here would either overwrite a cancel already recorded or race the run
 *                that legitimately holds the task.
 * `unusable`  — the CAS SUCCEEDED (workflow_run_id is now bound to this run) but the context
 *                the task carries cannot support a bank pass. This run DOES hold the task, so
 *                it owes it a terminal state: settling nothing here would strand the row on
 *                both projections, which is precisely the defect _settle_wake_task exists to
 *                cure. Split out from `stand_down` deliberately — an earlier shape folded the
 *                two together and would have stranded every clientless or accountless task.
 */
export type ClaimOutcome =
  | { claimed: true; ctx: BankTaskContext }
  | { claimed: false; bound: false; reason: "not_running" | "bound_elsewhere" }
  | { claimed: false; bound: true; reason: "no_client" | "no_bank_account" };

/**
 * THE FIRST DURABLE ACT: CAS the task's own status and bind this run to it, in ONE statement.
 *
 * The predicate is the whole guard, and every conjunct earns its place:
 *   status = 'running'        — the engine's claim put it there. Off it (cancel_requested,
 *                               cancelled, failed, completed) this run must NOT act. #5.
 *   kind = 'wake'             — this body settles wake_outbox-carrier tasks only; a taskId
 *                               naming some other kind is a dispatch bug, refused rather than
 *                               acted on (review law 3: an id is not proof of its kind).
 *   run id null OR equal      — an unbound task binds to this run; a task ALREADY bound to this
 *                               same run is a legitimate WDK step replay and re-binds harmlessly;
 *                               a task bound to a DIFFERENT run means a second run exists for
 *                               this task and THIS one stands down. #8.
 *
 * A same-status UPDATE is lawful: _tf_agent_task_update gates the transition matrix inside
 * `if new.status <> old.status`, and workflow_run_id is not in its immutable-identity list
 * (0133:377-448, read directly — not inferred from the design prose).
 */
export async function claimBankTask(c: PgExec, taskId: string, workflowRunId: string): Promise<ClaimOutcome> {
  const upd = await c.query(
    `update clara.agent_tasks
        set workflow_run_id = $2
      where id = $1 and kind = 'wake' and status = 'running'
        and (workflow_run_id is null or workflow_run_id = $2)
      returning firm_id, client_id, origin_intent_id`,
    [taskId, workflowRunId],
  );
  if (upd.rowCount === 0) {
    // Distinguish the two no-op causes for the LOG only — both stand down identically. A row
    // still 'running' but bound elsewhere is #8; anything else is #5 (or a settled replay).
    const probe = await c.query(
      "select status, workflow_run_id from clara.agent_tasks where id = $1 and kind = 'wake'",
      [taskId],
    );
    const row = probe.rows[0];
    const boundElsewhere = row?.status === "running" && row?.workflow_run_id != null && row.workflow_run_id !== workflowRunId;
    return { claimed: false, bound: false, reason: boundElsewhere ? "bound_elsewhere" : "not_running" };
  }
  // FROM HERE ON THE TASK IS OURS — the UPDATE above committed workflow_run_id to this run — so
  // every refusal below is `bound: true` and the caller owes the task a terminal settle.
  // The RETURNING row is read POSITIVELY rather than asserted from rowCount: a non-zero rowCount
  // with no readable row would be a driver-level impossibility, and the honest answer to an
  // impossibility is the fail-closed branch, never a non-null assertion (review law 2).
  const row = upd.rows[0] ?? null;
  if (!row) return { claimed: false, bound: true, reason: "no_client" };
  const firmId = String(row.firm_id ?? "");
  const clientId = row.client_id == null ? "" : String(row.client_id);
  // The bank mint gate REQUIRES a firm-congruent active client (0133:745-752) and this body has
  // no lawful way to invent one — a clientless wake task cannot run this lane at all.
  if (!clientId) return { claimed: false, bound: true, reason: "no_client" };
  const evt = await readBankTaskContext(c, String(row.origin_intent_id ?? ""));
  if (!evt.bankAccountId) return { claimed: false, bound: true, reason: "no_bank_account" };
  return { claimed: true, ctx: { taskId, firmId, clientId, bankAccountId: evt.bankAccountId, dueReason: evt.dueReason } };
}

/**
 * THE BANK ACCOUNT COMES FROM THE EVENT, and this is a CONTRACT on the producer half, stated
 * here because this is where it is consumed.
 *
 * clara.wake_get_bank_pack REQUIRES a bank account (0121:5707-5709 raises CLR11 when the named
 * account is not the client's), and a pack is per-account: "the client's bank accounts" is not
 * a thing this lane can enumerate, because clara_wake_bank holds EXECUTE on thirteen wrappers
 * and no direct SELECT on clara.bank_accounts at all. So the account must arrive with the work.
 *
 * The wake_outbox carrier already carries a place for it: the originating domain event's own
 * payload. clara_runtime holds SELECT on clara.domain_events (measured on the rig, not assumed),
 * so the claim step can read it.
 *
 * THE PRODUCER'S OBLIGATION, in three parts, when F-A3 builds the due predicate and the
 * bank.agent_due emitter (both ABSENT today — grep-verified across packages/db/migrations and
 * packages/runtime/lib/leader.mjs). The last two were MEASURED against the rig, each by a red,
 * not read off a document:
 *
 *   1. The event payload carries "bank_account_id", and may carry "reason" (the due predicate's
 *      own named reason — unmatched_lines / reconcilable / retry_later, bank-agency Annex D).
 *   2. The event is appended CLIENT-SCOPED (p_client non-null). _tf_agent_task_insert's wake arm
 *      (0011:1223-1230) DERIVES the task's firm_id and client_id from wake_intents joined to
 *      domain_events — a client_id supplied on the task INSERT is discarded — so a firm-level
 *      event yields a CLIENTLESS wake task, which the bank credential mint cannot serve.
 *   3. clara.event_types registers 'bank.agent_due' with client_scoped = TRUE. That flag is not
 *      cosmetic: clara._append_event refuses a client_id on a firm-level type outright
 *      (CLR10 "firm-level event <type> must not carry a client_id"), so a type registered
 *      firm-level can NEVER satisfy (2), and the source would wake tasks no lane can run.
 *
 * All three are exercised by the battery's own fixture (tests/g1-wake-bodies.fixtures.mjs).
 *
 * An event without one is NOT guessed around: the run stands down and the task settles 'failed'
 * with a named error, which is the loud, visible failure this seam should have. Absence is not
 * evidence (review law 2) — a missing account is a missing account, never "all accounts".
 */
export async function readBankTaskContext(c: PgExec, intentId: string): Promise<{ bankAccountId: string; dueReason: string | null }> {
  if (!intentId) return { bankAccountId: "", dueReason: null };
  const r = await c.query(
    `select de.payload
       from clara.wake_intents wi
       join clara.domain_events de on de.id = wi.event_id
      where wi.id = $1`,
    [intentId],
  );
  const payload = (r.rows[0]?.payload ?? null) as { bank_account_id?: unknown; reason?: unknown } | null;
  const acct = payload?.bank_account_id;
  const reason = payload?.reason;
  return {
    bankAccountId: typeof acct === "string" ? acct : "",
    dueReason: typeof reason === "string" ? reason : null,
  };
}

/** Settle through clara._settle_wake_task — the ONE settlement verb, which writes agent_tasks
 *  AND the paired wakes_outbox projection in the same transaction so the two views of one fact
 *  can never diverge (0133:503-542). Idempotent by its own construction: a re-settle replay
 *  finds the outbox row already settled and affects zero rows there, never a raise, and
 *  error_code is first-write-wins so a later replay can never erase the first cause. */
export async function settleBankTask(c: PgExec, taskId: string, outcome: "completed" | "failed", errorCode: string | null): Promise<void> {
  await c.query("select clara._settle_wake_task($1,$2,$3)", [taskId, outcome, errorCode]);
}

/** Resolve the language model. Production uses the OpenAI provider with the snapshot id; a test
 *  injects a mock through globalThis, so no network and no key ever enters a test. Reuses
 *  chatTurn's own override name so one mock arms every lane. */
export function resolveModel(modelId: string): unknown {
  const override = (globalThis as unknown as { __claraModelForTest?: unknown }).__claraModelForTest;
  return override ?? openai(modelId);
}

/**
 * Run fn on a clara_wake_bank connection with a FRESH bank_agent credential bound txn-locally.
 *
 * The credential is minted HERE, inside the calling step's own execution, and discarded when
 * this function returns — it is never an argument to a step, never a step's return value, and
 * never workflow state (the secret law, wake-mints.mjs's own header and MUST F). A retried step
 * attempt mints fresh rather than reusing a credential that may have aged past its TTL.
 */
export async function bankScoped<T>(ctx: { firmId: string; clientId: string }, fn: (c: PgExec) => Promise<T>): Promise<T> {
  const { secret } = await pools().mintBankAgentCredential(ctx.firmId, ctx.clientId, BANK_CREDENTIAL_TTL);
  return pools().withBankWakeScoped(secret, fn);
}

/** The op-key shape every bank act in this lane uses.
 *
 *  THE COLON FIELD IS LOAD-BEARING, not cosmetic. 0129's digest-freshness check binds a write's
 *  inputs digest to the CURRENT TASK by reading split_part(op_key, ':', 2) (0129:1005, :1048)
 *  — so putting the task id at field 2 buys the TIGHTER binding: a digest read for one task can
 *  no longer ground an act on another. 0129 falls back to a client+digest-only match when the
 *  key carries no parseable task field, which is the looser contract the unattended lane's own
 *  fixtures happened to get; this lane opts INTO the strict one.
 *
 *  DETERMINISM IS THE OTHER HALF. A WDK replay must produce the SAME key, or the estate's
 *  op-key idempotency cannot recognise the replay and the act runs twice. Every field below is
 *  derived from durable inputs (the task id, the act name, the call ordinal within the run) —
 *  never a clock, never a random. */
export function bankOpKey(verb: string, taskId: string, ordinal: number, subject: string): string {
  return `bank-${verb}:${taskId}:${ordinal}:${subject}`;
}
