// @frozen
//
// FROZEN — the bankAgent_v1 workflow entry (Gate G1's bank follow-up). A NEW frozen workflow
// CLASS: the export the wake engine dispatches for the 'bank_agent' source, which
// clara.wake_engine_sources already names as workflow_export 'bankAgent' (migration 0133 §G,
// seeded enabled=false). See bankAgent.v1.infra.ts for the closure's full statement of intent.
// Do NOT edit this file or its import closure once deployed — ship a change as bankAgent_v2.
//
// NO BACKTICKS IN THIS FILE'S COMMENTS, AND THAT IS NOT A STYLE RULE. The Workflow DevKit
// detects a "use workflow" directive by blanking template literals with a naive regex before it
// looks for the directive line, so a stray backtick in a comment above the directive can pair
// with one below it and blank the directive itself. The build then succeeds, the file is left
// untransformed, and the workflow is simply ABSENT from the registry. autoDraft.v9.ts hit
// exactly that and was caught only by the mandatory bundle grep; this file uses plain quotes
// throughout for the same reason.
//
// THE SHAPE OF A WAKE RUN, and the one thing that makes it different from every other lane:
// this body does not own its own admission. The engine already moved the task held->running and
// committed before start() was ever called, so by the time this function runs the books ALREADY
// say a bank run is in flight. Every exit path below therefore ends in a settle — completed or
// failed — because a wake task that is never settled is a stranded row on TWO projections
// (agent_tasks and wakes_outbox), which is the exact defect clara._settle_wake_task exists to
// cure. The one exception is the stand-down, and it is deliberate: see below.

import { claimBankTaskStep, runBankAgentModelStep, settleBankTaskStep } from "./bankAgent.v1.impl.js";

/** Reduce a caught top-level error to the settle record's own error_code. The roster is the
 *  agent_tasks CHECK's closed set (0006_runtime_core.sql:153-154) — model_error, tool_error,
 *  timeout, engine_lost, limit, internal — so a value outside it can never reach the column and
 *  turn a truthful failure into a constraint violation. Anything unrecognised lands on
 *  'internal', which is the honest answer to "we do not know", never a guess dressed up. */
export function bankErrorCode(err: unknown): "model_error" | "tool_error" | "timeout" | "internal" {
  const message = err instanceof Error ? err.message : String(err);
  if (/\btimeout\b|\btimed out\b/i.test(message)) return "timeout";
  if (/\btool\b/i.test(message)) return "tool_error";
  if (/\bmodel\b|\bprovider\b/i.test(message)) return "model_error";
  return "internal";
}

export async function bankAgent_v1(input: { taskId: string }): Promise<{ taskId: string; outcome: string }> {
  "use workflow";
  const taskId = input.taskId;
  let settled = false;
  // HOLDS IS THE SETTLE'S OWN PRECONDITION, and it is not bookkeeping. A settle is only this
  // run's to make once the CAS has actually bound the task to it. Before that, the task may be
  // held by a DIFFERENT run (the #8 shape) or already settled by a reconciler, and a settle from
  // here would overwrite someone else's truth. The catch block below is exactly where that
  // matters: if claimBankTaskStep ITSELF throws — after WDK step retries are exhausted — we
  // never learned whether we hold the task, so we must NOT settle. The row then sits
  // running-with-no-run, which is precisely the shape reconciler-wake.mjs section A picks up and
  // re-enqueues past grace: visible, recoverable, never stranded.
  let holds = false;
  const settle = async (outcome: "completed" | "failed", errorCode: string | null) => {
    if (settled || !holds) return;
    settled = true;
    await settleBankTaskStep(taskId, outcome, errorCode);
  };

  try {
    // THE CLOSING WALL, first and unconditionally. A false claim means one of two things, and
    // in BOTH the correct act is to do nothing at all:
    //   - the task is no longer 'running' (a cancel landed in the window between the engine's
    //     enqueue commit and this bind, or a reconciler already settled it), or
    //   - it is bound to a DIFFERENT run (a crash-recovery re-enqueue started a second one).
    // NOTHING IS SETTLED ON THE UNBOUND PATH, and that is the point rather than an omission:
    // the row is already spoken for by whoever moved it, and a settle from here would either
    // overwrite a cancel that has already been recorded or race the run that legitimately holds
    // the task. A no-op exit, never an error — the same "duplicate start self-aborts" idiom
    // reconciler-wake.mjs's own header invokes for crash recovery.
    const claim = await claimBankTaskStep(taskId);
    if (!claim.claimed) {
      // THE BOUND HALF IS THE OPPOSITE CASE, and folding the two together would strand rows.
      // A `bound: true` refusal means the CAS SUCCEEDED — workflow_run_id now names this run —
      // and only then did the task turn out to carry no client or no bank account. This run
      // holds the task, so it owes it a terminal state; walking away would leave it 'running'
      // forever on both projections. Both causes are producer-side contract breaches (see
      // readBankTaskContext for the contract this lane depends on), so they settle FAILED and
      // say so, rather than being papered over with a guessed account.
      if (claim.bound) {
        holds = true;
        await settle("failed", "internal");
        return { taskId, outcome: `failed:${claim.reason}` };
      }
      return { taskId, outcome: `stood_down:${claim.reason}` };
    }
    holds = true;

    const ctx = claim.ctx;
    const modelId = process.env.CLARA_BANK_AGENT_MODEL || process.env.CLARA_CHAT_MODEL || "gpt-5.6-terra";

    const run = await runBankAgentModelStep(ctx, modelId);
    if (run.outcome.kind === "refused") {
      await settle("failed", run.outcome.code === "model_error" ? "model_error" : "internal");
      return { taskId, outcome: "failed" };
    }
    // Both remaining outcomes are truthful successes: the pass read the pack and either acted
    // or lawfully found nothing due. The DURABLE record of WHAT it did is the receipts the bank
    // verbs wrote in their own transactions (clara.bank_agent_receipts, written inside
    // _agent_bank_receipt by every core) — this settle records only that the run finished.
    await settle("completed", null);
    return { taskId, outcome: run.outcome.kind };
  } catch (err) {
    // A thrown run still owes its task a terminal state, or the row strands on both
    // projections. The settle is best-effort so a settle failure cannot swallow the original
    // cause; reconciler-wake.mjs's own belt picks up whatever this could not finish.
    await settle("failed", bankErrorCode(err)).catch(() => {});
    throw err instanceof Error ? err : new Error(String(err));
  }
}
