// @frozen
//
// BINDING versioning policy (ARCHITECTURE Appendix A, spike T6): a deployed workflow
// body is IMMUTABLE once any run can be in flight. Self-hosted WDK has NO run-pinning
// — an in-place edit silently changes the un-executed remainder of every parked run.
// So DO NOT edit this file (or its import closure: chatTurn.impl.ts, chatTurn.prompt.ts)
// once deployed. Ship a behavioural change as chatTurn.v2.ts and repoint the registry.
// The MODEL ID is the ONE run-scoped parameter (durably snapshotted per task at
// admission — S4-D3); everything else here is frozen. The CI freeze-lint hash-locks
// this file + its whole relative-import closure.
//
// chatTurn_v1 — the durable chat turn (contract §4.2/§4.3). Read-only advisor:
//   load task snapshot -> load history + client context pack -> loop model segments,
//   CHECKPOINTING each segment durably (S4-AB6) and streaming it to the run's writable;
//   if the model calls `clarify`, mint a RANDOM hook token in a memoized step (S4-AB4),
//   open the clarify ATOMICALLY (clara.open_interruption), and park until a firm member
//   answers (or it expires/cancels); settle idempotently (usage recovered from the
//   checkpoints). The ENTIRE body is wrapped in try/finally so EVERY exit path closes
//   the stream writable (S4-AB4b, P2 stream-close law).

import { createHook } from "workflow";
import type { ModelMessage } from "ai";
import {
  claimRunStep,
  loadTaskStep,
  loadContextStep,
  runModelSegmentStep,
  mintHookTokenStep,
  openInterruptionStep,
  checkpointStep,
  markRunningStep,
  settleStep,
  closeStreamStep,
} from "./chatTurn.impl.js";
import { CLARIFY_FRAMING, type ClaraPart } from "./chatTurn.prompt.js";

const MAX_SEGMENTS = 12; // hard bound on clarify round-trips per turn (safety)

export async function chatTurn_v1(input: { taskId: string }): Promise<{ taskId: string; outcome: string; segments: number }> {
  "use workflow";
  const taskId = input.taskId;
  const messages: ModelMessage[] = [];
  const allParts: ClaraPart[] = [];
  let outcome: "completed" | "failed" | "expired" | "cancelled" = "completed";
  let segment = 0;

  // Settle exactly once (guarded) — tokens come from the durable checkpoints (the DB
  // ignores the passed count), so we pass 0; parts are the in-memory accumulation.
  let settled = false;
  const settle = async (o: typeof outcome, errorCode: string | null) => {
    if (settled) return;
    settled = true;
    await settleStep(taskId, allParts, 0, o, errorCode);
  };

  try {
    // Claim this task for THIS run (S4-AB3). A duplicate start finds it already bound
    // and self-aborts — no model call, no settle — so exactly one run does the work.
    const claim = await claimRunStep(taskId);
    if (!claim.claimed) {
      return { taskId, outcome: "deduped", segments: 0 }; // the finally closes our stream
    }

    const task = await loadTaskStep(taskId);
    const ctx = await loadContextStep(task.sessionId, task.clientId, task.firmId);
    for (const m of ctx.history) messages.push(m);
    const systemExtra = ctx.contextPack
      ? `Client context pack (books_version is the freshness token):\n${JSON.stringify(ctx.contextPack)}`
      : "";

    for (; segment < MAX_SEGMENTS; segment++) {
      const seg = await runModelSegmentStep(task.model, task.clientId, task.firmId, messages, systemExtra);
      await checkpointStep(taskId, segment, seg.usageTokens, seg.parts); // durable per-segment (AB6)
      for (const p of seg.parts) allParts.push(p);

      if (!seg.clarify) {
        outcome = "completed";
        break;
      }

      // The model asked for a human decision. Append its turn, then park on a hook
      // whose token is RANDOM (minted in a memoized step — stable across replays, no
      // §8 reuse footgun). open_interruption atomically parks the task + opens the clarify.
      messages.push({ role: "assistant", content: seg.assistantContent } as unknown as ModelMessage);
      const hookToken = await mintHookTokenStep();
      const hook = createHook<{ kind: "answer" | "expired" | "cancelled"; answer?: unknown }>({ token: hookToken });
      await openInterruptionStep(taskId, hookToken, { question: seg.clarify.question, context: seg.clarify.context });

      const resolution = await hook; // PARK — zero compute until answered/expired/cancelled

      if (resolution.kind === "answer") {
        await markRunningStep(taskId); // un-park: awaiting_input -> running
        messages.push({
          role: "tool",
          content: [
            {
              type: "tool-result",
              toolCallId: seg.clarify.toolCallId,
              toolName: "clarify",
              output: { type: "json", value: resolution.answer ?? null },
            },
          ],
        } as unknown as ModelMessage);
        continue;
      }

      // expired / cancelled — record a closed part and settle accordingly.
      allParts.push({ type: "clarify_closed", reason: resolution.kind, framing: CLARIFY_FRAMING });
      outcome = resolution.kind;
      break;
    }
    if (segment >= MAX_SEGMENTS) outcome = "completed"; // safety bound reached

    await settle(outcome, null);
  } catch (err) {
    // A model/tool/step failure that survived the engine's step retries. Settle the
    // task visibly-failed (running->failed is matrix-legal); the reconciler is the net.
    await settle("failed", "model_error").catch(() => {});
    throw err instanceof Error ? err : new Error(String(err));
  } finally {
    // IDEMPOTENT close on EVERY exit path (S4-AB4b) — load failure, model error, settle
    // failure, cancel, expiry: the readable always reaches done.
    await closeStreamStep().catch(() => {});
  }

  return { taskId, outcome, segments: segment + 1 };
}
