// @frozen
//
// BINDING versioning policy (ARCHITECTURE Appendix A, spike T6): a deployed workflow
// body is IMMUTABLE once any run can be in flight. Self-hosted WDK has NO run-pinning
// — an in-place edit silently changes the un-executed remainder of every parked run.
// So DO NOT edit this file (or its import closure: chatTurn.impl.ts, chatTurn.prompt.ts).
// Ship a behavioural change as chatTurn.v2.ts and repoint workflows/registry.ts.
// The MODEL ID is the ONE run-scoped parameter (durably snapshotted per task at
// admission — S4-D3); everything else here is frozen. The CI freeze-lint hash-locks
// this file + its whole relative-import closure.
//
// chatTurn_v1 — the durable chat turn (contract §4.2/§4.3). Read-only advisor:
//   load task snapshot -> load history + client context pack -> loop model segments,
//   streaming each to the run's writable; if the model calls `clarify`, park on a
//   fresh per-segment hook until a firm member answers (or it expires/cancels);
//   settle idempotently; CLOSE the stream writable exactly once (P2 stream-close law).

import { createHook } from "workflow";
import type { ModelMessage } from "ai";
import {
  loadTaskStep,
  loadContextStep,
  runModelSegmentStep,
  recordInterruptionStep,
  markRunningStep,
  settleStep,
  closeStreamStep,
} from "./chatTurn.impl.js";
import { CLARIFY_FRAMING, type ClaraPart } from "./chatTurn.prompt.js";

const MAX_SEGMENTS = 12; // hard bound on clarify round-trips per turn (safety)

export async function chatTurn_v1(input: { taskId: string }): Promise<{ taskId: string; outcome: string; segments: number }> {
  "use workflow";
  const taskId = input.taskId;
  const task = await loadTaskStep(taskId);
  const { history, contextPack } = await loadContextStep(task.sessionId, task.clientId, task.firmId);

  const systemExtra = contextPack
    ? `Client context pack (books_version is the freshness token):\n${JSON.stringify(contextPack)}`
    : "";

  const messages: ModelMessage[] = [...history];
  const allParts: ClaraPart[] = [];
  let totalTokens = 0;
  let outcome: "completed" | "failed" | "expired" | "cancelled" = "completed";
  let segment = 0;

  try {
    for (; segment < MAX_SEGMENTS; segment++) {
      const seg = await runModelSegmentStep(task.model, task.clientId, task.firmId, messages, systemExtra);
      totalTokens += seg.usageTokens;
      for (const p of seg.parts) allParts.push(p);

      if (!seg.clarify) {
        outcome = "completed";
        break;
      }

      // The model asked for a human decision. Append its turn, then park on a FRESH
      // per-segment hook (re-armed per segment — the S4-V2 bounded-hook fallback).
      messages.push({ role: "assistant", content: seg.assistantContent } as unknown as ModelMessage);
      const hookToken = `clarify:${taskId}:${segment}`;
      const hook = createHook<{ kind: "answer" | "expired" | "cancelled"; answer?: unknown }>({ token: hookToken });
      await recordInterruptionStep(taskId, hookToken, { question: seg.clarify.question, context: seg.clarify.context });

      const resolution = await hook; // PARK — zero compute until answered/expired/cancelled

      if (resolution.kind === "answer") {
        await markRunningStep(taskId); // un-park: awaiting_input -> running
        messages.push({
          role: "tool",
          content: [
            {
              type: "tool-result",
              toolCallId: seg.clarify.toolCallId,
              toolName: "clarify",
              output: { type: "json", value: resolution.answer ?? null },
            },
          ],
        } as unknown as ModelMessage);
        continue;
      }

      // expired / cancelled — record a closed part and settle accordingly.
      allParts.push({ type: "clarify_closed", reason: resolution.kind, framing: CLARIFY_FRAMING });
      outcome = resolution.kind;
      break;
    }
    if (segment >= MAX_SEGMENTS) outcome = "completed"; // safety bound reached
  } catch (err) {
    // A model/tool/step failure that survived the engine's step retries. Settle the
    // task visibly-failed and close the stream; the reconciler is the further net.
    await settleStep(taskId, allParts, totalTokens, "failed", "model_error").catch(() => {});
    await closeStreamStep().catch(() => {});
    throw err instanceof Error ? err : new Error(String(err));
  }

  await settleStep(taskId, allParts, totalTokens, outcome, null);
  await closeStreamStep();
  return { taskId, outcome, segments: segment + 1 };
}
