// @frozen
//
// BINDING versioning policy (docs/architecture/ARCHITECTURE.md Appendix A,
// Slice-0 finding T6): a deployed workflow body is IMMUTABLE once any run can be
// in flight. On self-hosted WDK there is no run-pinning — an in-place edit
// silently changes the semantics of the un-executed remainder of every parked
// run. So DO NOT edit this file. Ship any behavioural change as a NEW export
// (closeExample.v2.ts) and repoint workflows/registry.ts to it, retaining v1
// until zero non-terminal runs reference it.
//
// The CI freeze-lint (scripts/check-frozen-workflows.mjs) golden-hashes this
// file and FAILS the build if the body changes without going through --update.

import { recordExample } from "./steps.js";

export async function closeExampleV1(
  opKey: string,
): Promise<{ workflow: string; opKey: string; recordedAt: string }> {
  "use workflow";
  const rec = await recordExample(opKey);
  return { workflow: "closeExample.v1", opKey: rec.opKey, recordedAt: rec.recordedAt };
}
