// @frozen
//
// FROZEN — part of the closePrep_v1 closure (Gate G1's close follow-up: the workflow body the
// wake engine dispatches for the 'close_prep' source, which clara.wake_engine_sources already
// names as workflow_export 'closePrep', carrier 'direct_queue', seeded enabled=false).
// A NEW frozen workflow CLASS. ARCHITECTURE Appendix A: do not edit this file or any member of
// its import closure (closePrep.v1 / .impl / .tools / .prompt / .usage) once deployed — ship a
// behavioural change as closePrep_v2.
//
// THREE THINGS ABOUT THIS LANE ARE UNLIKE bankAgent_v1, and each is measured, not assumed:
//
//  1. THE CARRIER. close_prep rides the direct_queue carrier: the task is born 'queued' (not
//     'held') and carries its own client_id, with no wake_intents/domain_events chain behind it.
//     So the claim CAS reads 'running' the same way, but there is no event payload to consult —
//     the client is on the task row itself.
//
//  2. THE CREDENTIAL MUST BE TASK-BOUND. Every one of 0138's twelve wrappers routes through
//     clara._close_wake_ctx, which calls clara._wake_task_id() and raises CLR03
//     wake_task_unbound on a NULL (0138:1302-1306). A credential from the ordinary
//     mint_wake_credential door records no agent_task_id, so it mints fine and is then refused
//     by every verb it could call. mintWakeCredentialForTask is the only door that works here.
//
//  3. THE OP KEY IS DERIVED BY THE DATABASE, NOT CHOSEN. _close_wake_ctx recomputes
//     sha256(task ‖ ':' ‖ verb ‖ ':' ‖ subject) and refuses anything else as
//     'op_key_not_derived' (0138:1266-1269, :1311-1314). The deliberate design there is that a
//     wrapper-minted key would defeat _reserve_op's retry semantics and a free-form key would
//     let a caller replay yesterday's outcome. So this file recomputes the SAME hash rather
//     than inventing one — see closeOpKey.
//
// THE ROLE. All twelve wrappers are granted to clara_wake_interactive (0138:2539-2553,
// read directly), which the WRITE pool reaches: clara_wake_write_login, SET ROLE
// clara_wake_interactive per checkout (pools.mjs). There is no dedicated close login and none
// is owed — no new secret or ceremony rides with this lane, unlike the bank one.

import { createHash } from "node:crypto";
import { openai } from "@ai-sdk/openai";

export type PgExec = {
  query(sql: string, params?: unknown[]): Promise<{ rows: Array<Record<string, unknown>>; rowCount: number | null }>;
};

export type ClosePools = {
  withRuntime<T>(fn: (c: PgExec) => Promise<T>): Promise<T>;
  withWriteWakeScoped<T>(secret: string, fn: (c: PgExec) => Promise<T>): Promise<T>;
  mintWakeCredentialForTask(
    wakeKind: string,
    firmId: string,
    clientId: string,
    agentTaskId: string,
    ttl?: string,
  ): Promise<{ secret: string }>;
};

export function pools(): ClosePools {
  const p = (globalThis as unknown as { __claraPools?: ClosePools }).__claraPools;
  if (!p) throw new Error("runtime pools not injected (globalThis.__claraPools) — the supervisor must inject them at boot");
  return p;
}

export const CLOSE_CREDENTIAL_TTL = process.env.CLARA_CLOSE_PREP_CREDENTIAL_TTL || "5 minutes";

export type CloseTaskContext = { taskId: string; firmId: string; clientId: string };

/** Same three verdicts, same reason, as bankAgent_v1's — see that file's own note. `bound: true`
 *  means the CAS committed and this run OWES the task a terminal settle; `bound: false` means
 *  the task belongs to someone else and this run must settle nothing. */
export type ClaimOutcome =
  | { claimed: true; ctx: CloseTaskContext }
  | { claimed: false; bound: false; reason: "not_running" | "bound_elsewhere" }
  | { claimed: false; bound: true; reason: "no_client" };

/**
 * THE FIRST DURABLE ACT: CAS the task's own status and bind this run, in ONE statement. This is
 * the closing wall wake-engine.mjs's module header names as this build's obligation (#5/#8) —
 * see bankAgent.v1.infra.ts's claimBankTask for the full statement of what each conjunct closes.
 * The only difference here is `kind = 'close_prep'`, the direct_queue carrier's own kind.
 *
 * A same-status UPDATE is lawful: _tf_agent_task_update gates the transition matrix inside
 * `if new.status <> old.status`, and workflow_run_id is not in its immutable-identity list
 * (0133:377-448, read directly).
 */
export async function claimCloseTask(c: PgExec, taskId: string, workflowRunId: string): Promise<ClaimOutcome> {
  const upd = await c.query(
    `update clara.agent_tasks
        set workflow_run_id = $2
      where id = $1 and kind = 'close_prep' and status = 'running'
        and (workflow_run_id is null or workflow_run_id = $2)
      returning firm_id, client_id`,
    [taskId, workflowRunId],
  );
  if (upd.rowCount === 0) {
    const probe = await c.query(
      "select status, workflow_run_id from clara.agent_tasks where id = $1 and kind = 'close_prep'",
      [taskId],
    );
    const row = probe.rows[0];
    const boundElsewhere = row?.status === "running" && row?.workflow_run_id != null && row.workflow_run_id !== workflowRunId;
    return { claimed: false, bound: false, reason: boundElsewhere ? "bound_elsewhere" : "not_running" };
  }
  // FROM HERE ON THE TASK IS OURS — read the RETURNING row POSITIVELY rather than asserting it
  // from rowCount: a non-zero rowCount with no readable row would be a driver-level
  // impossibility, and the honest answer to an impossibility is the fail-closed branch (which
  // here still settles, because the CAS committed), never a non-null assertion.
  const row = upd.rows[0] ?? null;
  if (!row) return { claimed: false, bound: true, reason: "no_client" };
  const clientId = row.client_id == null ? "" : String(row.client_id);
  // The task-bound mint REQUIRES a firm-congruent active client (0138:829-833), and every
  // wrapper's client pin requires the credential to name one. A clientless close_prep task
  // cannot run this lane at all — and it is OURS now, so it settles rather than stranding.
  if (!clientId) return { claimed: false, bound: true, reason: "no_client" };
  return { claimed: true, ctx: { taskId, firmId: String(row.firm_id ?? ""), clientId } };
}

/** Settle through clara._settle_wake_task — the same ONE verb both carriers use. A direct_queue
 *  task carries no wakes_outbox row at all, so the outbox cascade is skipped BY CONSTRUCTION
 *  there (v_intent is null), never by a missed match (0133:534-541). */
export async function settleCloseTask(c: PgExec, taskId: string, outcome: "completed" | "failed", errorCode: string | null): Promise<void> {
  await c.query("select clara._settle_wake_task($1,$2,$3)", [taskId, outcome, errorCode]);
}

export function resolveModel(modelId: string): unknown {
  const override = (globalThis as unknown as { __claraModelForTest?: unknown }).__claraModelForTest;
  return override ?? openai(modelId);
}

/**
 * Recompute the op key the DATABASE will derive for this (task, verb, subject).
 *
 * This mirrors clara._close_expected_op_key EXACTLY:
 *   encode(sha256(convert_to(task::text || ':' || verb || ':' || subject::text, 'UTF8')), 'hex')
 * A mismatch is not a silent divergence — _close_wake_ctx refuses with CLR10
 * 'op_key_not_derived' — so this function is checked by the database on every single call, which
 * is exactly the property that makes reimplementing a hash here safe rather than reckless.
 *
 * DETERMINISTIC BY CONSTRUCTION, which is the other half of why the DB derives it: a WDK replay
 * recomputes the identical key, so _reserve_op recognises the replay and returns the stored
 * outcome instead of acting twice. A new wake task is a new key, so a released hold is
 * re-MEASURED rather than replayed (0138:1259-1265).
 */
export function closeOpKey(taskId: string, verb: string, subjectId: string): string {
  return createHash("sha256").update(`${taskId}:${verb}:${subjectId}`, "utf8").digest("hex");
}

/**
 * Run fn on the WRITE pool (clara_wake_interactive) with a fresh TASK-BOUND close_prep
 * credential bound txn-locally. Minted here, used here, discarded on return — never a step
 * input, never a step return, never workflow state (the secret law).
 */
export async function closeScoped<T>(ctx: CloseTaskContext, fn: (c: PgExec) => Promise<T>): Promise<T> {
  const { secret } = await pools().mintWakeCredentialForTask("close_prep", ctx.firmId, ctx.clientId, ctx.taskId, CLOSE_CREDENTIAL_TTL);
  return pools().withWriteWakeScoped(secret, fn);
}
