// @frozen
//
// FROZEN — the closePrep_v1 workflow entry (Gate G1's close follow-up). A NEW frozen workflow
// CLASS: the export the wake engine dispatches for the 'close_prep' source, which
// clara.wake_engine_sources already names as workflow_export 'closePrep' (migration 0133 §G,
// carrier 'direct_queue', seeded enabled=false). See closePrep.v1.infra.ts for the closure's
// full statement of intent. Do NOT edit this file or its import closure once deployed — ship a
// behavioural change as closePrep_v2.
//
// NO BACKTICKS IN THIS FILE'S COMMENTS, AND THAT IS NOT A STYLE RULE. The Workflow DevKit
// detects a "use workflow" directive by blanking template literals with a naive regex before it
// looks for the directive line, so a stray backtick in a comment above the directive can pair
// with one below it and blank the directive itself. The build then succeeds, the file is left
// untransformed, and the workflow is simply ABSENT from the registry. autoDraft.v9.ts hit
// exactly that and was caught only by the mandatory bundle grep.
//
// EVERY EXIT PATH ENDS IN A SETTLE, except the unbound stand-down. The engine already moved the
// task queued->running and committed before start() was called, so the books already say a
// close-prep run is in flight; a run that walks away without settling leaves a stranded row,
// which is the exact defect clara._settle_wake_task exists to cure.

import { claimCloseTaskStep, runClosePrepModelStep, settleCloseTaskStep } from "./closePrep.v1.impl.js";

/** Reduce a caught top-level error to the settle record's own error_code. The roster is the
 *  agent_tasks CHECK's closed set (0006_runtime_core.sql:153-154), so a value outside it can
 *  never reach the column and turn a truthful failure into a constraint violation. Anything
 *  unrecognised lands on 'internal' — the honest answer to "we do not know". */
export function closeErrorCode(err: unknown): "model_error" | "tool_error" | "timeout" | "internal" {
  const message = err instanceof Error ? err.message : String(err);
  if (/\btimeout\b|\btimed out\b/i.test(message)) return "timeout";
  if (/\btool\b/i.test(message)) return "tool_error";
  if (/\bmodel\b|\bprovider\b/i.test(message)) return "model_error";
  return "internal";
}

export async function closePrep_v1(input: { taskId: string }): Promise<{ taskId: string; outcome: string }> {
  "use workflow";
  const taskId = input.taskId;
  let settled = false;
  // HOLDS IS THE SETTLE'S OWN PRECONDITION — see bankAgent.v1.ts for the full statement. In
  // short: a settle is only this run's to make once the CAS has bound the task to it. If
  // claimCloseTaskStep itself throws (after WDK step retries are exhausted) we never learned
  // whether we hold the task, so we must NOT settle. BOTH reconciler branches cover the
  // aftermath and both are named on purpose: §A reenqueueStuckRows takes the UNBOUND row (this
  // case), §B settleFromEngineTruth takes the BOUND one (a claim that committed then lost its
  // connection, and our own settle throwing — `settled` is set before the await, so the catch
  // does not retry it). A row is either bound or it is not; there is no third state to strand in.
  let holds = false;
  const settle = async (outcome: "completed" | "failed", errorCode: string | null) => {
    if (settled || !holds) return;
    settled = true;
    await settleCloseTaskStep(taskId, outcome, errorCode);
  };

  try {
    // THE CLOSING WALL, first and unconditionally. An UNBOUND refusal means the task is no
    // longer this run's to touch — a cancel landed, or a crash-recovery re-enqueue started a
    // second run that holds it. NOTHING IS SETTLED on that path, deliberately: a settle from
    // here would either overwrite a cancel already recorded or race the run that legitimately
    // holds the task. A no-op exit, never an error.
    const claim = await claimCloseTaskStep(taskId);
    if (!claim.claimed) {
      // A BOUND refusal is the opposite case: the CAS succeeded and workflow_run_id now names
      // this run, and only then did the task turn out to carry no client. This run holds the
      // task, so it owes it a terminal state — walking away would strand it 'running' forever.
      if (claim.bound) {
        holds = true;
        await settle("failed", "internal");
        return { taskId, outcome: `failed:${claim.reason}` };
      }
      return { taskId, outcome: `stood_down:${claim.reason}` };
    }
    holds = true;

    const ctx = claim.ctx;
    const modelId = process.env.CLARA_CLOSE_PREP_MODEL || process.env.CLARA_CHAT_MODEL || "gpt-5.6-terra";

    const run = await runClosePrepModelStep(ctx, modelId);
    if (run.outcome.kind === "refused") {
      await settle("failed", run.outcome.code === "model_error" ? "model_error" : "internal");
      return { taskId, outcome: "failed" };
    }
    // Both remaining outcomes are truthful successes: the pass read the books and either
    // proposed or lawfully found nothing due. The DURABLE record of WHAT it did is the receipts
    // the wrappers wrote in their own transactions (clara.agent_act_receipts, via
    // _agent_close_receipt) plus any clara.close_proposals row wake_propose_close created —
    // this settle records only that the run finished.
    await settle("completed", null);
    return { taskId, outcome: run.outcome.kind };
  } catch (err) {
    // A thrown run still owes its task a terminal state. The settle is best-effort so a settle
    // failure cannot swallow the original cause; reconciler-wake.mjs's belt picks up the rest.
    await settle("failed", closeErrorCode(err)).catch(() => {});
    throw err instanceof Error ? err : new Error(String(err));
  }
}
