// @frozen
//
// payrollFacts_v1 — THE PAYROLL SUMMARY'S OWN QUESTIONNAIRE FAMILY, on the `payroll_facts` lane.
// #945; parent #926, owner ruling 2026-09-18 (option G): "a payroll summary and a contract go
// down the same lane as any other accounting document, read and posted, not merely stored."
//
// A BRAND-NEW CLASS, not a version of witnessFacts, and the ticket says why in its own first
// acceptance criterion: a versioned workflow may not couple its shape to another family's frozen
// files. Everything this family can ever need to change on its own — the questionnaire, the wire
// schema, the behaviour, the database reads, the entry — is its own; what it shares (the provider
// adapter, the temp-file lifecycle, the region numbering) is infrastructure that is not frozen
// and not a questionnaire.
//
// WHAT CLARA DOES HERE, IN ONE SENTENCE: she reads a payroll summary twice — once through the
// text channel, once through the vision channel — reports what each page PRINTS, quotes every
// employee row the page shows, and hands both readings to a deterministic evaluator that does
// every sum. She never adds anything up. She never fills a blank with zero. A figure the page
// does not print is reported as not printed.
//
// DEPLOY ORDER IS DATABASE FIRST, RUNTIME SECOND (migration 0296's header states it and this
// file's behaviour holds the other side): the persist door validates the answer envelope, so an
// image that answered a wider questionnaire than the live validator admits would be refused on
// every persist. In the other order the router's new lane simply queues tasks this image drains.
//
// Do NOT edit this file or its import closure once deployed (ARCHITECTURE Appendix A
// immutability). A behavioural change — INCLUDING A PROMPT TWEAK, which is why the prompts sit
// inside the closure — ships as payrollFacts.v2.ts with the registry repointed, and
// payrollFacts_v1 stays reachable until zero non-terminal runs reference it.

import {
  claimPayrollFactsTaskStepV1,
  payrollTextReadStepV1,
  payrollVisionReadStepV1,
  persistPayrollFactsStepV1,
} from "./payrollFacts.v1.impl.js";

export async function payrollFacts_v1(
  input: { task_id: string },
): Promise<{ task_id: string; outcome: string }> {
  "use workflow";
  const taskId = input.task_id;
  const claim = await claimPayrollFactsTaskStepV1(taskId);
  if (!claim.claimed) return { task_id: taskId, outcome: claim.status };
  // SEQUENTIAL, not concurrent: the two reads are independent, but running them one after the
  // other means a text-channel refusal costs no vision call. A spend decision, never a
  // correctness one.
  const textRead = await payrollTextReadStepV1(taskId, claim.doc);
  const visionRead = await payrollVisionReadStepV1(taskId, claim.doc);
  const result = await persistPayrollFactsStepV1(taskId, textRead, visionRead);
  return { task_id: taskId, outcome: result.status };
}
