// @frozen
//
// statementFacts_v4 — the successor to statementFacts_v3 on the `statement_facts` witness-pair
// lane. The BODY is v3's, unchanged line for line: claim, branch on the claimed task's own
// `lane`, two sequential memoized reads, one persist. Everything v4 changes is inside the closure
// this file imports, and all of it is one named handover item:
//
//   #1037  THE PER-LINE SOURCE CITATION, produced. #990 / migration 0291 gave
//          `clara.bank_statement_lines` `citation_extraction_id` / `citation_page` /
//          `citation_region` and taught `clara._persist_statement_core_v2` to bank them off
//          reader1's own raw payload lines — but nothing could state one, because v3's line
//          schema carries no page and no region and `toWriterLines` rebuilds every line from six
//          named keys. Both are frozen, so the producer half was owed to a version cut. v4 asks
//          the TEXT reader, for each statement line, which numbered region it read that row from,
//          and resolves that index back to the region's own page and
//          `clara.document_regions.locator` before the payload is built. A line the reader could
//          not honestly cite persists uncited, and the Matching tab says so in words — #990's
//          own three-state face, which is unchanged by this version.
//
// WHY THE TEXT CHANNEL. The numbered region list is shown only to the text channel, and 0291's
// splice reads `v_r1->'lines'` — reader1, which is the text read. The written contract
// (`CUT-PLAN.md` section 3.2, `reports/wave3-lane08-ticket990.md`) says "the vision-channel
// prompt"; that is the one line of it that cannot be built as written, and
// statementFacts.v4.prompts.mjs's header carries the measurement.
//
// WHY THIS IS A NEW VERSION AND NOT AN EDIT (ARCHITECTURE Appendix A / `.claude/rules/
// runtime-workflows.md`): the change is behavioural AND it is inside the PROMPT closure, which
// for this family is a body change by decision M8. v3 stays exported and frozen until zero
// non-terminal statementFacts_v3 runs reference it — as do v2 and v1.
//
// NO MIGRATION, NO CEREMONY, NO DEPLOY ORDER. v4 calls the SAME verb
// (`clara.persist_statement_facts_v2(p_task uuid, p_payload jsonb)`, unchanged in name and
// argument order) under the SAME engine snapshot and the SAME injected services bundle. 0291 —
// applied 2026-09-20, long before this image — already widened what that verb accepts and already
// carries the column, the CHECK and the persist core's guard, so there is no window in which a v4
// payload meets a DB that cannot read it. A rollback to v3 is fail-closed for free: a v3 payload
// simply states no citation per line, which is the state every line is in today. The one thing
// this version needs is a runtime image; the registry entry does the rest.
//
// THE TWO LANES, UNCHANGED FROM v3:
//   `statement_facts`  -> THE WITNESS PAIR: a text channel + a vision channel, each its own
//                         memoized step, then ONE persist.
//   `statement_parse`  -> the structured csv/ofx lane, carried over BEHAVIOURALLY UNCHANGED —
//                         reached by IMPORTING v1's own claim + process steps
//                         (statementFacts.v4.impl.ts), never by copying them. It never egresses,
//                         still calls `clara.persist_statement_facts` (unchanged), and has no
//                         page concept at all — 0291's core REFUSES a citation on that lane.
//
// Do NOT edit this file or its import closure once deployed. A behavioural change — INCLUDING A
// PROMPT TWEAK — ships as statementFacts.v5.ts with the registry repointed, and this export stays
// reachable until zero non-terminal runs reference it.

import { claimStatementFactsTaskStep, processStatementFactsTaskStep } from "./statementFacts.v1.impl.js";
import {
  persistStatementWitnessPairStep,
  statementWitnessTextReadStep,
  statementWitnessVisionReadStep,
} from "./statementFacts.v4.impl.js";

export async function statementFacts_v4(
  input: { task_id: string },
): Promise<{ task_id: string; outcome: string; lane?: string }> {
  "use workflow";
  const taskId = input.task_id;
  const claim = await claimStatementFactsTaskStep(taskId);
  if (!claim.claimed) return { task_id: taskId, outcome: claim.status };

  if (claim.doc?.lane === "statement_facts") {
    // SEQUENTIAL, not concurrent — witnessFacts.v1's own reasoning applies unchanged: the two
    // reads are independent and each is its own memoized step, but running them one after the
    // other means a text-channel refusal costs no vision call.
    const textRead = await statementWitnessTextReadStep(taskId, claim.doc);
    const visionRead = await statementWitnessVisionReadStep(taskId, claim.doc);
    const result = await persistStatementWitnessPairStep(taskId, textRead, visionRead);
    return { task_id: taskId, outcome: result.status, lane: "statement_facts" };
  }

  // `statement_parse` (and, defensively, any other lane a stray claim could carry — v1's own
  // `processStatementFactsBehavior` returns `no_work` for a lane it does not recognise rather
  // than driving it) — the unchanged structured path, reached by IMPORTING v1's step.
  const result = await processStatementFactsTaskStep(taskId, claim.doc);
  return { task_id: taskId, outcome: result.status, lane: result.lane };
}
