// @frozen
//
// statementFacts_v2 (F-A1 PR-4 — `docs/plan/active/f-a1-witness-pair-design.md` §3.7): the
// successor to statementFacts_v1, shipped BUILT, FROZEN and DELIBERATELY UNPOINTED — `registry.ts`
// still names statementFacts_v1 as the live `statementFacts:` entry, and moving that key is the
// LAST step of the cutover, not this one (see ACTIVATION below). It serves BOTH statement lanes,
// branching on the claimed task's own `lane` — the SAME documentIngest ocr/structured_parse
// precedent statementFacts_v1 itself followed — but the branch now lives at the WORKFLOW level
// rather than inside one processing step, because the witness pair needs its own two memoized
// model-call steps (witnessFacts.v1's own §3.1 shape) while the structured lane still needs
// only one:
//
//   `statement_facts`  -> THE WITNESS PAIR (NEW): a text channel + a vision channel, each its
//                         own memoized step, then ONE persist via
//                         `clara.persist_statement_facts_v2`.
//   `statement_parse`  -> the structured csv/ofx lane, carried over from statementFacts_v1
//                         BEHAVIOURALLY UNCHANGED — reached by IMPORTING v1's own claim + process
//                         steps (statementFacts.v2.impl.ts), never by copying them. It never
//                         egresses and still calls `clara.persist_statement_facts` (unchanged).
//
// WHY THE LANE NAME STAYS `statement_facts` RATHER THAN MOVING TO `llm_witness`. `llm_witness`
// is witnessFacts_v1's own lane, claimed by `ownsWitnessLane` on lane alone, and the invoice
// dispatcher `_invoice_fact_state` resolves the witness regime by `t.lane='llm_witness'` — so a
// statement task sitting in that lane would be evaluated as an INVOICE. `statement_facts`
// already carries everything this pair needs: it is already bound to the global kill switch in
// `claim_document_processing_task`'s lane list (Wave C-b, unchanged by this PR), and the
// reconciler's `enqueueForLane` allowlist already routes it to the `statementFacts:` registry
// entry. So this version needs no new lane and no new admission path — but it is NOT reached by
// a repoint alone, and saying so would be false.
//
// ACTIVATION — A BOUND FOLLOW-UP PIECE, NOT SOMETHING THIS PR PERFORMS. `statement_facts` is a
// LIVE lane: its tasks are minted today, so the registry key IS the routing and pointing it at
// v2 takes production traffic the moment the image deploys. Until the DB router arm re-aims the
// statement engine literal from `azure-di:prebuilt-bankStatement.us:2024-11-30` to the witness
// snapshot `llm-openai:{model}:stmt-witness-v1`, every live statement task would arrive here
// stamped AZURE — and `assertStatementEngineStamp` would correctly WAIT rather than egress under
// a receipt naming a model it did not call. Those waits occupy the SHARED ocr concurrency window
// (`statement_facts` is not M10-windowed), so they would starve intake OCR as well as
// themselves. The order is therefore binding, and this PR is only its first step:
//
//   (1) the DB persist verb (this PR's 0098_f_a1_statements migration)
//   (2) PR-3 merges (it owns the wb-0020-pinned `_enqueue_invoice_facts_core` body)
//   (3) the router/consent arm migration on top of PR-3's body: the engine-literal re-aim plus
//       the statement typed-consent lookup moving to purpose `witness_extraction`
//   (4) ONLY THEN registry.ts: `statementFacts: statementFacts_v1` -> `statementFacts_v2`.
//
// The engine literal in step (3) and the snapshot in statementFacts.v2.services.mjs must
// STRING-EQUAL each other — statementFacts_v2 compares them BEFORE any egress and stalls the
// lane on a mismatch rather than mis-stamping a receipt. That pairing carries its own battery
// cell in the follow-up piece, not here.
//
// Do NOT edit this file or its import closure once deployed (ARCHITECTURE Appendix A
// immutability). A behavioural change — INCLUDING A PROMPT TWEAK (design M8, inherited from
// witnessFacts_v1: the prompts sit inside the closure by decision) — ships as
// statementFacts.v3.ts with the registry repointed, and this export stays reachable until zero
// non-terminal runs reference it.

import { claimStatementFactsTaskStep, processStatementFactsTaskStep } from "./statementFacts.v1.impl.js";
import {
  persistStatementWitnessPairStep,
  statementWitnessTextReadStep,
  statementWitnessVisionReadStep,
} from "./statementFacts.v2.impl.js";

export async function statementFacts_v2(
  input: { task_id: string },
): Promise<{ task_id: string; outcome: string; lane?: string }> {
  "use workflow";
  const taskId = input.task_id;
  const claim = await claimStatementFactsTaskStep(taskId);
  if (!claim.claimed) return { task_id: taskId, outcome: claim.status };

  if (claim.doc?.lane === "statement_facts") {
    // SEQUENTIAL, not concurrent — witnessFacts.v1's own reasoning applies unchanged: the two
    // reads are independent and each is its own memoized step, but running them one after the
    // other means a text-channel refusal costs no vision call.
    const textRead = await statementWitnessTextReadStep(taskId, claim.doc);
    const visionRead = await statementWitnessVisionReadStep(taskId, claim.doc);
    const result = await persistStatementWitnessPairStep(taskId, textRead, visionRead);
    return { task_id: taskId, outcome: result.status, lane: "statement_facts" };
  }

  // `statement_parse` (and, defensively, any other lane a stray claim could carry — v1's own
  // `processStatementFactsBehavior` returns `no_work` for a lane it does not recognise rather
  // than driving it) — the unchanged structured path, reached by IMPORTING v1's step.
  const result = await processStatementFactsTaskStep(taskId, claim.doc);
  return { task_id: taskId, outcome: result.status, lane: result.lane };
}
