// @frozen
//
// statementFacts_v3 — the successor to statementFacts_v2 on the `statement_facts` witness-pair
// lane. The BODY is v2's, unchanged line for line: claim, branch on the claimed task's own
// `lane`, two sequential memoized reads, one persist. Everything v3 changes is inside the
// closure this file imports, and all of it is one of three named handover items:
//
//   H-02  a statement that prints a STATEMENT DATE and no from–to band gets its period band
//         derived from that date's calendar month — opening on the first of the month, closing
//         ON THE STATEMENT DATE — with the basis recorded on the persisted `corroboration`
//         receipt. A statement that prints neither still refuses `header_unreadable`, exactly
//         as v2 does. The prompt's own internal contradiction on this field is gone.
//   H-03  the printed institution NAME is resolved to the `clara.bank_institutions` roster CODE
//         before the persist ("ALLIANCE BANK" -> ALB, "MAYBANK" -> MBB), and a name that
//         resolves to no single roster row REFUSES, naming what was printed and what it matched.
//   H-05  a failed persist SETTLES its task through `clara.fail_statement_facts` instead of
//         leaving `document_processing_tasks.status = 'running'` forever, and the reason it
//         settles with is the DB's own DETAIL token rather than a blanket `internal`.
//
// WHY THIS IS A NEW VERSION AND NOT AN EDIT (ARCHITECTURE Appendix A / `.claude/rules/
// runtime-workflows.md`): every one of the three changes is behavioural, and two of them are
// inside the PROMPT closure, which for this family is a body change by decision M8. v2 stays
// exported and frozen until zero non-terminal statementFacts_v2 runs reference it.
//
// NO MIGRATION, NO CEREMONY, NO DEPLOY ORDER. v3 sends the SAME wire vocabulary v2 sent —
// `_stmt_header_norm` reads a fixed field list and v3 adds no key to it — to the SAME verb
// (`clara.persist_statement_facts_v2`, unchanged), under the SAME engine snapshot and the SAME
// injected services bundle. So there is no window in which a v3 payload meets a DB that cannot
// read it, and a rollback to v2 is fail-closed for free: a v2 payload simply carries no header
// bases in its corroboration block, which is a field nothing verifies. The one thing this
// version needs is a runtime image; the registry entry does the rest.
//
// THE TWO LANES, UNCHANGED FROM v2:
//   `statement_facts`  -> THE WITNESS PAIR: a text channel + a vision channel, each its own
//                         memoized step, then ONE persist.
//   `statement_parse`  -> the structured csv/ofx lane, carried over BEHAVIOURALLY UNCHANGED —
//                         reached by IMPORTING v1's own claim + process steps
//                         (statementFacts.v3.impl.ts), never by copying them. It never egresses
//                         and still calls `clara.persist_statement_facts` (unchanged).
//
// Do NOT edit this file or its import closure once deployed. A behavioural change — INCLUDING A
// PROMPT TWEAK — ships as statementFacts.v4.ts with the registry repointed, and this export
// stays reachable until zero non-terminal runs reference it.

import { claimStatementFactsTaskStep, processStatementFactsTaskStep } from "./statementFacts.v1.impl.js";
import {
  persistStatementWitnessPairStep,
  statementWitnessTextReadStep,
  statementWitnessVisionReadStep,
} from "./statementFacts.v3.impl.js";

export async function statementFacts_v3(
  input: { task_id: string },
): Promise<{ task_id: string; outcome: string; lane?: string }> {
  "use workflow";
  const taskId = input.task_id;
  const claim = await claimStatementFactsTaskStep(taskId);
  if (!claim.claimed) return { task_id: taskId, outcome: claim.status };

  if (claim.doc?.lane === "statement_facts") {
    // SEQUENTIAL, not concurrent — witnessFacts.v1's own reasoning applies unchanged: the two
    // reads are independent and each is its own memoized step, but running them one after the
    // other means a text-channel refusal costs no vision call.
    const textRead = await statementWitnessTextReadStep(taskId, claim.doc);
    const visionRead = await statementWitnessVisionReadStep(taskId, claim.doc);
    const result = await persistStatementWitnessPairStep(taskId, textRead, visionRead);
    return { task_id: taskId, outcome: result.status, lane: "statement_facts" };
  }

  // `statement_parse` (and, defensively, any other lane a stray claim could carry — v1's own
  // `processStatementFactsBehavior` returns `no_work` for a lane it does not recognise rather
  // than driving it) — the unchanged structured path, reached by IMPORTING v1's step.
  const result = await processStatementFactsTaskStep(taskId, claim.doc);
  return { task_id: taskId, outcome: result.status, lane: result.lane };
}
