// @frozen
//
// witnessFacts_v2 (F-A2 openers ①②) — the successor to witnessFacts_v1 on the `llm_witness` lane.
// The WORKFLOW BODY IS UNCHANGED from v1: claim, text read, vision read, one atomic persist. What
// changed is entirely inside the closure it drives, and it is two things:
//
//   ② THE TYPE_CODE PROMPT. v1 asked for "the printed document-type code", which real Malaysian
//     paper invoices never print — so both channels honestly answered `not_printed` on every
//     document and the evaluator's M12 conjunct could never pass (measured 0/33 in the live
//     corpus run). v2 asks the model to CLASSIFY the document, with the carve-out from the
//     verbatim rule named and scoped to that one field.
//   ① THE NIL-TAX ARM'S EVIDENCE. A new asked-and-answered `invoice.sst_registration` (party-
//     blind, never belt-required, answered on both channels, NEVER cited) plus the
//     `witness.coverage` receipt — the OCR generation the text channel actually read, whether its
//     region block was truncated, and which fields this read DOWNGRADED. Without those,
//     `clara.evaluate_witness_fact_state_v2`'s three locks would each be reading a silence.
//
// THE DEPLOY ORDER IS DB-FIRST, RUNTIME-SECOND — THE OPPOSITE OF THE PR-3 CUTOVER'S RULE, and it
// is binding. This image sends `invoice.sst_registration` in every envelope; a pre-widened
// `clara._witness_answers_ok` refuses an unknown answer key with CLR10 (0095:220-221), which
// would abort EVERY persist and wedge the whole invoice lane. With the DB half applied first the
// order is harmless in both directions, and a rollback to witnessFacts_v1 is fail-closed for
// free: v1 envelopes simply carry no SST answer and no coverage receipt, so the arm never fires
// and v2's evaluator degrades exactly to v1 behaviour.
//
// THE ENGINE ID MOVES WITH THIS CLASS. witnessFacts.v2.services.mjs stamps
// `llm-openai:{model}:v2` and injects under its OWN global; the same window's DB migration moves
// the router's literal from `:v1` to `:v2`. Until both halves are live the behaviour's
// pre-egress provenance guard WAITS rather than egressing under a receipt naming a prompt
// closure that did not read the document — the fail-closed direction, in both orders.
//
// Do NOT edit this file or its import closure once deployed (ARCHITECTURE Appendix A
// immutability). A behavioural change — INCLUDING A PROMPT TWEAK, which is why the prompts sit
// inside the closure by decision M8 — ships as witnessFacts.v3.ts with the registry repointed,
// and witnessFacts_v1 stays reachable until zero non-terminal runs reference it.

import {
  claimWitnessFactsTaskStepV2,
  persistWitnessFactsStepV2,
  witnessTextReadStepV2,
  witnessVisionReadStepV2,
} from "./witnessFacts.v2.impl.js";

export async function witnessFacts_v2(
  input: { task_id: string },
): Promise<{ task_id: string; outcome: string }> {
  "use workflow";
  const taskId = input.task_id;
  const claim = await claimWitnessFactsTaskStepV2(taskId);
  if (!claim.claimed) return { task_id: taskId, outcome: claim.status };
  // SEQUENTIAL, not concurrent — the two reads are independent and each is its own memoized
  // step, but running them one after the other means a text-channel refusal costs no vision
  // call. Ordering them is a spend decision, never a correctness one.
  const textRead = await witnessTextReadStepV2(taskId, claim.doc);
  const visionRead = await witnessVisionReadStepV2(taskId, claim.doc);
  const result = await persistWitnessFactsStepV2(taskId, textRead, visionRead);
  return { task_id: taskId, outcome: result.status };
}
