// @frozen
//
// witnessFacts_v3 (the NEXT-ROUND QUEUE fold) — the successor to witnessFacts_v2 on the
// `llm_witness` lane. THE WORKFLOW BODY IS UNCHANGED from v2: claim, text read, vision read, one
// atomic persist. What changed is entirely inside the closure it drives — five fixes banked out
// of the 2026-08-21 F-A2 openers re-measure and the owner's 2026-08-24 discount-no-net ruling
// (`docs/plan/completed/f-a2-window-ab-ceremony-asrun.md` §13; PROGRESS.md "THE NEXT-ROUND
// QUEUE"; full fold in witnessFacts.v3.prompts.mjs's header):
//
//   1. the MYR currency-code fix (a FALSE-refusal repair — "RINGGIT MALAYSIA" now answers as a
//      code, 'RM'/'MYR', instead of failing the evaluator's alphabetic-membership test);
//   2. the dash-is-not-a-value clarification (a bare '-'/'—'/'NIL' in an amount position answers
//      'not_printed' on BOTH channels, closing the cross-channel agreement mismatch that cost
//      both BRIGHTPATH documents);
//   3. a vision-only reinforcement to look twice for the bare SST-registration shape (lock 3's
//      margin on the corpus's one genuine registrant was a single channel, not two);
//   4. the discount-no-net ruling (owner, 2026-08-24): a printed discount is never license to
//      derive a net by subtraction — the prompt now asks explicitly whether the document prints
//      a SEPARATE net/subtotal line, extracting it when printed and refusing (not_printed) when
//      it is not, even beside a visible discount;
//   5. dropping `coverage.pages` from the text-channel receipt (witnessFacts.v3.envelope.mjs) —
//      it was emitted empty on every row in the re-measure, no lock reads it, and the finding's
//      own recommendation was fix-or-drop; this ships the drop, since the root cause (page
//      numbers absent upstream) is outside this fold's scope.
//
// NO DB CHANGE OF ANY KIND RIDES WITH THIS VERSION. Unlike v1->v2 (which added the
// `invoice.sst_registration` answer key and therefore needed `_witness_answers_ok` widened
// DB-first), every fix above is prompt wording or a receipt member drop — the wire schema is
// byte-identical to v2's. This image can deploy and the registry can repoint with NO coupled
// migration and NO deploy-order ceremony; see witnessFacts.v3.impl.ts's header for why it reuses
// v2's own injected services bundle rather than minting a new one.
//
// Do NOT edit this file or its import closure once deployed (ARCHITECTURE Appendix A
// immutability). A behavioural change — INCLUDING A PROMPT TWEAK, which is why the prompts sit
// inside the closure by decision M8 — ships as witnessFacts.v4.ts with the registry repointed,
// and witnessFacts_v2 (and v1) stay reachable until zero non-terminal runs reference them.

import {
  claimWitnessFactsTaskStepV3,
  persistWitnessFactsStepV3,
  witnessTextReadStepV3,
  witnessVisionReadStepV3,
} from "./witnessFacts.v3.impl.js";

export async function witnessFacts_v3(
  input: { task_id: string },
): Promise<{ task_id: string; outcome: string }> {
  "use workflow";
  const taskId = input.task_id;
  const claim = await claimWitnessFactsTaskStepV3(taskId);
  if (!claim.claimed) return { task_id: taskId, outcome: claim.status };
  // SEQUENTIAL, not concurrent — unchanged from v1/v2: the two reads are independent and each is
  // its own memoized step, but running them one after the other means a text-channel refusal
  // costs no vision call. Ordering them is a spend decision, never a correctness one.
  const textRead = await witnessTextReadStepV3(taskId, claim.doc);
  const visionRead = await witnessVisionReadStepV3(taskId, claim.doc);
  const result = await persistWitnessFactsStepV3(taskId, textRead, visionRead);
  return { task_id: taskId, outcome: result.status };
}
