// @frozen
//
// witnessFacts_v1 (F-A1 — `docs/plan/active/f-a1-witness-pair-design.md` §3.1): a NEW registered
// frozen workflow CLASS beside the byte-untouched documentIngest_v2, invoiceFacts_v1 and
// statementFacts_v1. It serves the new `llm_witness` lane: ONE claim, TWO independent reads of
// the same document through TWO channels of the same provider, ONE atomic idempotent persist.
//
//   text-witness   — the model reads the stored OCR text as NUMBERED regions and CITES the
//                    region it read each fact from; the server verifies every citation.
//   vision-witness — the model reads the ORIGINAL filed bytes, sees no regions, and contributes
//                    the VALUE only. The independence axis is the CHANNEL (G1.1), not the vendor.
//
// FOUR STEPS, AND THE SHAPE IS THE POINT. Each model call is its own memoized step, so a persist
// failure REPLAYS both stored envelopes instead of buying two more model calls; the persist is a
// single DB verb that writes both rows, both fact-region sets and the settle in one transaction.
// The workflow body itself decides nothing about the reading — it orders the steps and stops.
//
// PR-2 SHIPS THIS CLASS BUT NOTHING MINTS ITS TASKS YET. `_enqueue_invoice_facts_core` never
// assigns lane='llm_witness' at this frontier (0090 §7e is deliberately inert) and the
// reconciler's `enqueueForLane` allowlist does not name the lane — both by design, so the image
// lands and is verified live BEFORE PR-3 flips the router (design §6, the positive-read law).
//
// Do NOT edit this file or its import closure once deployed (ARCHITECTURE Appendix A
// immutability). A behavioural change — INCLUDING A PROMPT TWEAK, which is why the prompts sit
// inside the closure by decision M8 — ships as witnessFacts.v2.ts with the registry repointed,
// and this export stays reachable until zero non-terminal runs reference it.

import {
  claimWitnessFactsTaskStep,
  persistWitnessFactsStep,
  witnessTextReadStep,
  witnessVisionReadStep,
} from "./witnessFacts.v1.impl.js";

export async function witnessFacts_v1(
  input: { task_id: string },
): Promise<{ task_id: string; outcome: string }> {
  "use workflow";
  const taskId = input.task_id;
  const claim = await claimWitnessFactsTaskStep(taskId);
  if (!claim.claimed) return { task_id: taskId, outcome: claim.status };
  // SEQUENTIAL, not concurrent — the two reads are independent and each is its own memoized
  // step, but running them one after the other means a text-channel refusal costs no vision
  // call. Ordering them is a spend decision, never a correctness one.
  const textRead = await witnessTextReadStep(taskId, claim.doc);
  const visionRead = await witnessVisionReadStep(taskId, claim.doc);
  const result = await persistWitnessFactsStep(taskId, textRead, visionRead);
  return { task_id: taskId, outcome: result.status };
}
